### ISSUE TITLE
Using the Torch with TVICameraCapturer

### ISSUE THREAD

**Issue by patreu22** [twilio/video-quickstart-ios#121]
Hello,

I'm using the Twilio SDK (currently on beta14) to connect a web user and an iPhone user for a video chat. The web user is able to turn the torchlight on and off for the iPhone user by a Pubnub message. That triggers the following method:
```
    func turnCameraLightOn(_ on: Bool) {
        if self.captureDeviceForTorch != nil {
            do {
                try self.captureDeviceForTorch!.lockForConfiguration()
                if (!on) {
                    self.captureDeviceForTorch!.torchMode = AVCaptureTorchMode.off
                } else {
                    do {
                        try self.captureDeviceForTorch!.setTorchModeOnWithLevel(1.0)
                    } catch {
                        print(error)
                    }
                }
                self.captureDeviceForTorch!.unlockForConfiguration()
            } catch {
                print(error)
            }
        }
    }
```

This setup worked for the last time but since today it doesn't work anymore.
The video stream interrupts and freezes. 
I get the following output to the console:

```
2017-05-04 17:10:19.454901 Briggen[642:182933] INFO:TwilioVideo:[Platform]:Session interrupted with reason: 3
2017-05-04 17:10:19.455063 Briggen[642:182933] INFO:TwilioVideo:[Platform]:... Capture pipeline did stop.
2017-05-04 17:10:19.455144 Briggen[642:182933] DEBUG:TwilioVideo:[Platform]:Teardown video pipeline ...
2017-05-04 17:10:19.455220 Briggen[642:182933] DEBUG:TwilioVideo:[Platform]:Finished video pipeline teardown.
2017-05-04 17:10:19.455292 Briggen[642:182933] DEBUG:TwilioVideo:[Platform]:Video pipeline did finish running
2017-05-04 17:10:19.456111 Briggen[642:182933] DEBUG:TwilioVideo:[Platform]:Interruption is not recoverable, will not attempt to resume.
2017-05-04 17:10:19.456589 Briggen[642:182933] INFO:TwilioVideo:[Platform]:Session stopped running
```

After disabling the camera light again I the video stream continues and I get the following console output:

```
2017-05-04 17:26:07.484003 Briggen[642:185963] DEBUG:TwilioVideo:[Core]:Sending a ping message..
2017-05-04 17:26:07.484929 Briggen[642:185963] WARN:TwilioVideo:[Signaling]:RESIP::TRANSPORT: Can't find matching transport [ V4 126.0.0.156:0 TCP target domain=unspecified mFlowKey=0 ]
2017-05-04 17:26:07.486181 Briggen[642:185963] INFO:TwilioVideo:[Signaling]:RESIP::TRANSPORT: tid=f791f43ffabb7761 failed to find a transport to [ V4 54.172.60.105:5061 TCP target domain=unspecified mFlowKey=0 ]
2017-05-04 17:26:07.641554 Briggen[642:185943] INFO:TwilioVideo:[Platform]:Session interruption ended
2017-05-04 17:26:07.641757 Briggen[642:185943] INFO:TwilioVideo:[Platform]:Session started running
2017-05-04 17:26:07.667477 Briggen[642:187209] DEBUG:TwilioVideo:[Platform]:Video pipeline will start running
```

Do you have any idea how to troubleshoot that?

Thanks in advance
Patrick

**Comment by ceaglest** [comment]
Hi @patreu22,

My apologies for the delayed response. I know you also engaged support about this issue, but I'd like to discuss the issue here so others can benefit.

From Zack Pitts, and myself:

>Thanks for checking with us, and sorry for the trouble. First off, did you know we've released the official 1.0.0 SDK for GA? I recommend you upgrade your current beta build:
>
> https://www.twilio.com/docs/api/video/download-video-sdks#ios-sdk
>
> Secondly, as you may have already noticed, we don't currently support APIs for manual camera controls like torch, zoom, or exposure but we are considering adding these features to TVICameraCapturer in the future. (I've added your interest to that feature request.)
>
> Unfortunately, since the operations you're performing aren't synchronized with our internal session queue there could be some stability issues, which would account for why it works sometimes and sometimes it doesn't.
>
> If you don't mind, would you please describe your use case and desired flow so we can take a look at your specific needs as we consider future enhancements to the SDK?
>
> Please let me know. Thanks!

In the meantime, one suggestion I will make is you could try modifying the capture device before creating a TVILocalVideoTrack (this causes capture to start). If you could describe the order of operations you are taking at the moment we may be able to help with a workaround.

Best,
Chris Eagleston

**Comment by ceaglest** [comment]
Hi @patreu22,

I modified the QuickStart sample app to enable the torch when using the back wide camera. I found that as long as I waited for capture to start, and then modified the device it seemed to work fine with no interruptions to the AVCaptureSession managed by TVICameraCapturer. Hopefully this will tide you over until we have time to officially add support for this feature.

https://github.com/ceaglest/video-quickstart-swift/tree/issue-121/use-torch-example

Best,
Chris Eagleston

**Comment by patreu22** [comment]
Hey Christ,

this is very nice of you, thanks for helping me out with enabling the torch. I found out the error just occurs while the front camera is used and the torch is turned on. If the back camera is selected everything is working fine, so I was able to create a simple workaround for that.

I would be really happy about adding these feature to one of your APIs objects.

Thank you very much for your great support and help!

**Comment by ceaglest** [comment]
Hi @patreu22,

No problem, I'm glad to hear that you were able to get the torch working with the back camera. I'm going to leave this ticket open until we have time to add this feature to TVICameraCapturer, and so others can see the "unofficial" solution that I linked.

Thanks,
Chris Eagleston

**Comment by ceaglest** [comment]
Hi,

This is an old issue, but it is still something we are thinking about. Our latest release [2.6.0-preview1](https://www.twilio.com/docs/video/changelog-twilio-video-ios-version-2x#260-preview1-december-3-2018) introduces a new class called `TVICameraSource`. While the first version doesn't have APIs to use the torch, we are considering this for 2.6.0-preview2.

I will keep this ticket up to date as the new APIs evolve.

Best,
Chris

**Comment by ceaglest** [comment]
We've shipped APIs to use the torch with [TVICameraSource](https://twilio.github.io/twilio-video-ios/docs/latest/Categories/TVICameraSource+AVCaptureDeviceControl.html). Try our [3.0.1](https://www.twilio.com/docs/video/changelog-twilio-video-ios-version-3x#301-november-5-2019) release if you are interested in this functionality.
