### ISSUE TITLE
Issue: problems with TVILocalAudioTrack gain after updating SDK

### ISSUE THREAD

**Issue by Ponf** [twilio/video-quickstart-ios#151]
Hi!

I have updated my app to the latest version of Twilio iOS SDK and faced with strange issue: other participant almost stopped to hear me. He only hear if I knock directly in my phone's microphone. Other VoIP apps works fine, so I believe that it's not a problem with device.

I have checked `[[AVAudioSession sharedInstance] inputGain]`, it returns `1.0f`.

Also I have tried `TVIAudioOptions.levelControl`, but still without success :(
```objc
self.localAudioTrack = [TVILocalAudioTrack trackWithOptions:[TVIAudioOptions optionsWithBlock:^(TVIAudioOptionsBuilder * _Nonnull builder) {
      builder.levelControl = YES;
        }] enabled:YES];
```

**Comment by paynerc** [comment]
Hello Ponf,

Sorry to hear that you are having issues with the latest version. Can you tell me what version you were using when it worked and the version you are now working and seeing the issue?

Thanks!

Ryan

**Comment by Ponf** [comment]
@paynerc I have upgraded from 1.1.0 version, but now I've tried to downgrade version to 1.1 and still have same behaviour.

Also after I've tried to make a call using headphones with mic audio session worked correct, and participant heard me well!

I already tried to reinstall the app, cleaned project&derived data, restarted device. I have no ideas how to figure out the reason of my problem :(

**Comment by paynerc** [comment]
@Ponf,

Is the recipient of your video also on iOS? Is it running the same application? How is the `audioOutput` setting on the `TVIAudioController` configured?

Has anything else changed in your application that has coincided with the upgrade to `1.2.0` of Twilio Video?

Ryan

**Comment by Ponf** [comment]
@paynerc,

We have tried iOS and web clients, both of them almost didn't hear me.

> Has anything else changed in your application that has coincided with the upgrade to 1.2.0 of Twilio Video?
Nothing related to a call process

Thanks!
Filipp

**Comment by paynerc** [comment]
@Ponf,

I just released 1.2.1 of Twilio Video last evening. Can you validate that you are still having the issue?

Also, can you enable debug logging and provide me with the output? You can either attach a text file to this ticket or you can also open a support request, attach the file and reference that you are working with me and it will get routed to me.

To enable debug logging you can call `[TwilioVideo setLogLevel:TVILogLevelDebug]` before joining the room and replicating the issue.

Thanks! Looking forward to resolving this issue.

Ryan

**Comment by Ponf** [comment]
@paynerc,

I have updated my app to a latest version. Also I have distribute app to other testers (with version 1.2.1) and no one have same issues, so I believe I have some problems in my installation/configuration.

I'm attaching debug log. During this call participant almost didn't hear me until I've attached headphones. I don't think that it's a hardware issue because I have no problems with Facetime calls...

[debug log.txt](https://github.com/twilio/video-quickstart-swift/files/1142544/debug.log.txt)

**Comment by paynerc** [comment]
@Ponf,

I have received the logs and are starting to look through them.

One initial thought I had that might be useful...

`TVILocalAudioTrackStats` shows the input level of the local audio track. It might be useful for us to collect stats while the app is running to see what is being reported. Would be good to get the reading for the level before and after you attach the headphones.

Another question I failed to ask previously, what version of iOS are you running, and on which device? I have not been able to replicate the low audio issue you are seeing and would like to make sure my environment is the same as yours.

Ryan

**Comment by paynerc** [comment]
Also, can you enable the debug logging for WebRTC as well?

`[TwilioVideo setLogLevel:TVILogLevelDebug module:TVILogModuleWebRTC];`

Thanks!

**Comment by Ponf** [comment]
@paynerc how can I get access to a `TVILocalAudioTrackStats`? Didn't find according properties at `TVIAudioTrack`.

I'm using iPhone 6 running iOS 10.3.2

**Comment by paynerc** [comment]
I'm sorry, I should have been more clear. You can request stats to be collected from the room:

```
/**
 * @brief Retrieve stats for all media tracks.
 *
 * @param block The block to be invoked when the stats are available.
 *
 * @discussion Stats are retrieved asynchronously. In the case where the room is the `TVIRoomStateDisconnected` state,
 *             reports won't be delivered.
 */
- (void)getStatsWithBlock:(nonnull TVIRoomGetStatsBlock)block;
```

In my app, I have a timer that fires once a second that requests statistics to be collected. From there you can access the `TVILocalAudioTrackStats` from the `TVIStatsReport` objects that are passed into the block.

**Comment by Ponf** [comment]
@paynerc got it!

[log2.txt](https://github.com/twilio/video-quickstart-swift/files/1142677/log2.txt)

You can find audio level by looking for `Local Audio Track Level` in log. So until I have plugged in my headphones it wasn't higher than `300`, but after it was even `11406`.

Thanks!

**Comment by paynerc** [comment]
A few more questions for you:

* Are you using CallKit in your application?
* Are you using the `TVIAudioController configureAudioSession:` method?

**Comment by Ponf** [comment]
@paynerc,

> Are you using CallKit in your application?

Yes

> Are you using the TVIAudioController configureAudioSession: method?

Yes, I'm calling  `[[TVIAudioController sharedController] configureAudioSession:TVIAudioOutputVideoChatDefault];` in two cases:

1. Once I have received VoIP push about incoming call, right before showing CallKit UI
2. Once after I'm starting connection to a room

**Comment by paynerc** [comment]
@Ponf,

Would you be willing to try our CallKit quickstart sample app on that device and see if you are still experiencing the issue? I am wondering if there is something not being properly set up when joining the room and with how CallKit activates the audio session.

**Comment by ptankTwilio** [comment]
@Ponf Are you still observing the audio problem? 

Video SDK provides APIs to interact with audio when CallKit is used. Documentation [link](https://media.twiliocdn.com/sdk/ios/video/releases/1.3.0/docs/Categories/TVIAudioController+CallKit.html). Since CallKit activates the audio session at an elevated priority, so it is important to use SDK's CallKit APIs in a specific order. As Ryan mentioned, we have a sample app which demonstrates how to use Video SDK's CallKit APIs. 
Let us know if you are still observing the issue, we would be very happy to solve it.

**Comment by souvickcse** [comment]
Hi, What are the maximum and minimum values of TVILocalAudioTrackStats audioLevel?

**Comment by piyushtank** [comment]
0 to 127
https://tools.ietf.org/html/rfc6465
