### ISSUE TITLE
roomDidStartRecording Swift delegate method is not getting called.

### ISSUE THREAD

**Issue by Abhisheksnapwiz** [twilio/video-quickstart-ios#184]
When first user get connected to room able to perform the recording but **roomDidStartRecording** method is not getting called.

New participant got join and **participantDidConnect** method is getting called but **roomDidStartRecordingand** is not got called. I have created **group** room with enabled **recordParticipantsOnConnect** as **true**?

_I want to know when Twilio will come up with muxing feature for video with audio recording.?_

About Twilio use -
Product - Programmable Video

Twilio Helper Library or SDK for server side(Node js)-

JavaScript SDKs/Video/JavaScript
https://www.twilio.com/docs/api/video/download-video-sdks#javascript-sdk
npm install --save twilio-video

I am running local server to get access token, Create room and get recording SID's(Audio and video both).

**Comment by ptankTwilio** [comment]
@Abhisheksnapwiz Can you provide more details about your dev setup and the used case you are trying to achieve? From your note, it seems that you are expecting iOS Swift Callbacks while using the JavaScript SDK in your app? Please note that Video SDK is available in JavaScript SDK for web applications and iOS SDK for iOS Objective-C and Swift Application. At present JavaScript SDK is not supported for Swift, however, I encourage you to try out our iOS Video SDK for Swift application. 
Thanks and let me know if you have any questions.

**Comment by Abhisheksnapwiz** [comment]
@ptankTwilio  Thank you for your respone 

**- Dev Setup**
**Server--------**
I am running Node.js code on server side to generate the Access token and create the room and this I am running at my local machine. I am creating **group** room with enabled **recordParticipantsOnConnect** as **true**.

**Device --------** 
I have took reference from [video-quickstart-swift] (https://github.com/twilio/video-quickstart-swift). 
I am connecting to the room from device which  I have created on server side. Once I got connected to the room **didconnect** delegate method is getting called but **roomDidStartRecording** method is not getting call. When other participant joins the room then **participantDidConnect** is getting called but again **roomDidStartRecording** is not getting called.

**Use Case --------** 
I have created group room with recordParticipantsOnConnect setting as true.
I have to implement recording and Archiving feature where single user will join the room and I need to record video and Audio for this user (like user can tell about him self or reply for some question via video)
Due to not getting call back for **roomDidStartRecording** unable to know when recording will get start and if I am trying to consider recording starting point when user got connected to room getting some delay at beginning of recorded video.

Also I have one more question that I am unable stream the video using recording SID. I am trying to play the video in chrome, Firefox using url - Video -
https://video.twilio.com/v1/Recordings/RTXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/Media
I am authenticating then its getting downloaded instead of playing the video and How can I give username and password in url so that while using the url it will not popup the authentication popup.

**Comment by ptankTwilio** [comment]
@Abhisheksnapwiz Thanks for providing the details.

**Recording Callbacks:** 
Your observation is correct. At present iOS SDK does not provide `roomDidStartRecording:` or `roomDidStopRecording:` delegates, however, you can query `recording` property on `TVIRoom` object to check if the recording is started.  Alternatively, after creating the Group Room using the REST API, recording events will get dispatched to webhook URL specified at Room creation, see [this](https://www.twilio.com/docs/api/video/status-callbacks#rooms-status-callback-events) for REST API documentation. 

**Playing video on chrome**
Playing the recorded video directly on a browser is not supported. You will have to download the video first in order to play it on a browser or on a player. 

Please let me know if you have any further questions.

**Comment by Abhisheksnapwiz** [comment]
@ptankTwilio - StatusCallBacks is helpful for debugging but for implementation in device app delegate method are good. Due to not getting these call back when recording start and stop getting issue like starting of video frame and undefined when trying to download video on server side once  stoping the video recording from device.

_Just to know when Twilio development team will come up with these methods specially for video audio recording feature?_

**Comment by ceaglest** [comment]
Hey @Abhisheksnapwiz, 

I think your questions about the SDK level events, and REST API callbacks are answered in this issue:

https://github.com/twilio/video-quickstart-android/issues/187

Basically, recording is only ever "on" or "off" in a given Room. At the moment it will never change after Room creation so those events aren't fired. On the SDK side you can use the `isRecording` getter to determine if a Room is recording or not. On the server side you should be getting callbacks as described in the linked Android ticket when the Tracks finish post-processing.

Best,
Chris Eagleston
