### ISSUE TITLE
Is it possible to modify video captured by TVICameraCapturer?

### ISSUE THREAD

**Issue by marcinax** [twilio/video-quickstart-ios#194]
I would like to modify the video captured by camera before sending it to participants - add filters, colors in real time. I'm going to use for example this library: https://github.com/BradLarson/GPUImage, to filter live video from an iOS device's camera.

Currently, I simply use `TVICameraCapturer`:

    let camera = TVICameraCapturer(source: .frontCamera, delegate: self)
    localVideoTrack = TVILocalVideoTrack(capturer: camera!)

Is there any way to extend `TVICameraCapturer` or create my own capturer (based directly on camera) compatible with `TVILocalVideoTrack` and modify the frames/pixels before sending it?

**Comment by ptankTwilio** [comment]
@marcinax At present our Video SDK does not have any way to get the video frames from `TVICameraCapturer` for editing before sending it to the remote participant. Internally, we are discussing the solutions to support this feature. I will keep you posted when this becomes fully available in our SDK.  However, it is possible to achieve the used case by writing your own capturer. Your capturer should provide video frames to the SDK. To write your custom capturer, you will have to implement `TVIVideoCaptuerer` protocol. Our [ExampleScreenCaptuerer](https://github.com/twilio/video-quickstart-swift/blob/master/ScreenCapturerExample/ExampleScreenCapturer.swift#L10) example demonstrates how to write your own custom capture and provide frames to Video SDK.

Please let me know if you have any questions.
