### ISSUE TITLE
Adding ARKit with SpriteKit Example

### ISSUE THREAD

**Issue by AFathi** [twilio/video-quickstart-ios#205]
### Description
It would be great to add an example of implementing `ARKit` with `SpriteKit` in Twilio video chat!

I just recently published a new framework that provide the rendered buffers of both `SpriteKit` and `SceneKit` in a [protocol](https://github.com/AFathi/ARVideoKit/wiki/RecordAR#var-renderarrenderardelegate) [method](https://github.com/AFathi/ARVideoKit/wiki/RenderARDelegate#func-framedidrender-buffercvpixelbuffer-with-timecmtime-using-rawbuffercvpixelbuffer).

The framework is called [ARVideoKit](http://github.com/AFathi/ARVideoKit). It's currently close sourced; however, I'm planning to open source it in early 2018. Check the framework's [documentation](https://github.com/AFathi/ARVideoKit/wiki) for more information.

Additionally, I would love to contribute in this project by adding this feature to the ARKit example!

**Comment by ptankTwilio** [comment]
@AFathi Thanks for reaching out. Our [ARKitExample](https://github.com/twilio/video-quickstart-swift/tree/master/ARKitExample) demonstrate a very basic video call scenario, however, our [Customer-Designer](https://github.com/twilio/video-shared-arkit-sample) application demonstrates interactive video call using ARKit. 

Yes, your contributions are welcome to our sample apps, feel free to submit pull requests.

Let me know if you have any questions.

Best,
Piyush

**Comment by idelgado** [comment]
This is a blog that was published with the Customer-Designer sample @ptankTwilio referenced above: https://www.twilio.com/blog/2017/10/build-shared-ar-with-twilio-video-arkit-and-data-track.html

**Comment by AFathi** [comment]
Hey @ptankTwilio,
I just submitted a [pull request](https://github.com/twilio/video-quickstart-swift/pull/208) that includes a sample project demonstrating the use of both AR with SpriteKit and SceneKit content.

**Comment by piyushtank** [comment]
We have posted few review feedbacks on the PR. Closing an old ticket.
