### ISSUE TITLE
TwilioVideo - Battery drops very fast and device is very hot after 10 minutes.

### ISSUE THREAD

**Issue by newMobileStar** [twilio/video-quickstart-ios#229]
Hello Twilio Supprt.
I am happy to use Twilio SDK for developing an iOS video calling app between devices.
The video calling works well, but I face the this issue when I have a long time video call.
I used full screen mode for iOS devices. so In the Video constraint options, I setup 16:9 aspect ratio video dimension and try to add a frame per second with 10 fps to saving battery.

This is the objective-c code for Video constraints:

TVIVideoConstraints *videoConstraints = [TVIVideoConstraints constraintsWithBlock:
                                             ^(TVIVideoConstraintsBuilder * _Nonnull builder) {
                                                 builder.maxSize = TVIVideoConstraintsSize960x540;
                                                 builder.minSize = TVIVideoConstraintsSize960x540;
                                                 builder.minFrameRate = TVIVideoConstraintsFrameRate10;
                                                 builder.maxFrameRate = TVIVideoConstraintsFrameRate10;
                                             }];
    self.localVideoTrack = [TVILocalVideoTrack trackWithCapturer:self.camera enabled:YES constraints:videoConstraints];

But Battery % drops 1% per second, and very hot from 10 min call and more.
Btw, Video quality is too good rather than WhatsApp video call.

Is there any solution for implementing the long time video call with lowest battery drops and heat on the devices?
Please help me.
If we cannot fix this issue, we cannot use TwilioVideo.

- Video iOS SDK

Installed from the latest cocoapods

- Xcode9.2,

- iOS 11.2.5

**Comment by piyushtank** [comment]
@newMobileStar Thanks for reaching out. In order to debug the problem further, can you provide following information  - 

1. iOS device used 
2. TwilioVideo SDK Version
3. Are you trying a one-to-one call or multi-party call?
4. The topology: Are you using Group Rooms or P2P?
5. Is this problem specific to one device?  Are you are are observing the same problem on other devices as well?
6. what is the outcome when you use lower resolution ? for example, by default, when you do not provide any constraints the Video SDK will use 680x480 30fps.

I am sure we will be able to solve the problem together.

**Comment by ceaglest** [comment]
Hey @newMobileStar,

We would like to help out but need a little more information to move forward (see @piyushtank's post). Our 2.0 APIs have bandwidth controls which will save you some CPU cycles. Also capturing at 960x540x10 might end up making things harder on your phone than the default 640x480x30 especially if there is network related downscaling. Using H.264 over VP8 could also offer benefits depending on your use case.

Best,
Chris

**Comment by nomimalik1769** [comment]
I am having this same issue if anyone could resolve this its pain in the ***. 
**IOS Version: 11.2.5**
**Twilio Version: 2.0**
I am using default video values and my mobile is heating up and CPU usage is **75 to 85 %** after turning on live video chat.
**automatically fps is 58 sometimes 60 +.**

**Comment by newMobileStar** [comment]
Did you try to adjust bitrate (bit per second) ?

**Comment by newMobileStar** [comment]
@piyushtank Thank you for the info.

I use iOS device and full screen mode video constraint (980X540 : 16:9). 
and I am trying to do one-to-one P2P call.
I use TwilioVideo 2.0 
All devices face this issue.
I try to adjust fps and bps. do you have any suggestion to solve this issue ?

**Comment by piyushtank** [comment]
@newMobileStar @nomimalik1769 : As @ceaglest mentioned, capturing at 960x540x10 might end up making things harder on your phone than the default 640x480x30 especially if there is network related downscaling.  Have you tried H.264 video codecs? The H.264 codecs uses hardware encoding vs the VP8 software encoding. You should see the performance improvement for when the H.264 codec is used. Also, our 2.0 APIs have bandwidth controls which will save you some CPU cycles.

I would recommend trying H.264 video codec and bandwidth control. Please these out and let us know. You should see some performance improvements.

**Comment by piyushtank** [comment]
@newMobileStar Were you able to use the H.264 video codecs and bandwidth control in your app? Following should help using them in your sample app -

Code snippets to use H.264 video codecs in a Room -

```
let connectOptions = TVIConnectOptions.init(token: accessToken) { (builder) in

    // Use H.264 Codecs in Room
    builder.preferredVideoCodecs = [TVIVideoCodec.H264.rawValue]

    // Set maximum video bitrate in Room to 125MBPS . (The default videoBitrate is 2MBPS)
    builder.encodingParameters = TVIEncodingParameters(audioBitrate: 0, videoBitrate: 125000000)
}

// Connect to the Room using the options we provided.
room = TwilioVideo.connect(with: connectOptions, delegate: self)
```

Our Swift Quickstart supports this use case where you can select the video codecs and bitrate of your choice. -

1. Got to the settings view by clicking the "Settings" button on the top-right corner

<kbd><img width="300px" src="https://user-images.githubusercontent.com/17037593/37061590-cc1a9698-2148-11e8-9703-9a8975dce545.png"/></kbd>

2. You can select the codecs and the max bandwidth of your choice. I have set H.264 video codecs and 125 MBPS in the following example. I recommend trying it out.

<kbd><img width="300px" src="https://user-images.githubusercontent.com/17037593/37061513-9ed5b870-2148-11e8-96a4-bb73620c5452.PNG"/></kbd>


I recommend trying our Swift Quickstart and observe the performance on it first. With default settings (Default VP8 codecs with 640x480x30) in our experience, the swift quickstart performs at ~54-60% CPU utilization for one to one call with - 

![screen shot 2018-03-06 at 3 17 17 pm](https://user-images.githubusercontent.com/17037593/37064597-78d4e7d6-2152-11e8-9993-25a70487eb9f.png)

Let me know if you have any questions

**Comment by newMobileStar** [comment]
Ok let me try

Thank you for your help



On Mar 7, 2018, at 1:28 AM, Piyush Tank <notifications@github.com<mailto:notifications@github.com>> wrote:


@newMobileStar<https://github.com/newmobilestar> Were you able to use the H.264 video codecs and bandwidth control in your app? Following should help using them in your sample app -

Code snippets to use H.264 video codecs in a Room -

let connectOptions = TVIConnectOptions.init(token: accessToken) { (builder) in

    // Use H.264 Codecs in Room
    builder.preferredVideoCodecs = [TVIVideoCodec.H264.rawValue]

    // Set maximum video bitrate in Room to 125MBPS . (The default videoBitrate is 2MBPS)
    builder.encodingParameters = TVIEncodingParameters(audioBitrate: 0, videoBitrate: 125000000)
}

// Connect to the Room using the options we provided.
room = TwilioVideo.connect(with: connectOptions, delegate: self)


Our Swift Quickstart supports this use case where you can select the video codecs and bitrate of your choice. -

  1.  Got to the settings view by clicking the "Settings" button on the top-right corner

[https://user-images.githubusercontent.com/17037593/37061590-cc1a9698-2148-11e8-9703-9a8975dce545.png]<https://user-images.githubusercontent.com/17037593/37061590-cc1a9698-2148-11e8-9703-9a8975dce545.png>

  1.  You can select the codecs and the max bandwidth of your choice. I have set H.264 video codecs and 125 MBPS in the following example. I recommend trying it out.

[https://user-images.githubusercontent.com/17037593/37061513-9ed5b870-2148-11e8-96a4-bb73620c5452.PNG]<https://user-images.githubusercontent.com/17037593/37061513-9ed5b870-2148-11e8-96a4-bb73620c5452.PNG>

I recommend trying our Swift Quickstart and observe the performance on it first. With default settings (Default VP8 codecs with 640x480x30) in our experience, the swift quickstart performs at ~54-60% CPU utilization for one to one call with -

[screen shot 2018-03-06 at 3 17 17 pm]<https://user-images.githubusercontent.com/17037593/37064597-78d4e7d6-2152-11e8-9993-25a70487eb9f.png>

Let me know if you have any questions

**Comment by newMobileStar** [comment]
Another problem:

When I change the frame of Local Video track (self.previewView in the quickstart project) programmatically (e.g, from full screen to small sized screen), the video quality is surely changed Lower.

Is there any solution for this issue ?

**Comment by piyushtank** [comment]
@newMobileStar Did you get chance to try out the bandwidth and codec Connect options? If you use 1MBPS of bandwidth with 960x540x10, you should see the performance improvement. I have edited the code snippet in my last post on this ticket to use 1MBPS bandwidth.

**Comment by ceaglest** [comment]
> When I change the frame of Local Video track (self.previewView in the quickstart project) programmatically (e.g, from full screen to small sized screen), the video quality is surely changed Lower.

Changing the frame of `self.previewView` should not cause any difference in sent video quality, so there was likely another reason at play. Do you have a modified version of the QuickStart which demonstrates this issue?

**Comment by newMobileStar** [comment]
Btw, I have another question for TwilioVideo and TwilioVoice SDK.

in iOS, is there any way to retrieve the exact voice and video call data (duration, start time, end time, hold time etc)?

**Comment by ceaglest** [comment]
Hey @newMobileStar,

Piyush is out of the office right now, but let me see if I can help.

> but in the Twilio iOS SDKs, I cannot find out this like ones.
> 
> So in ios, is there any way to retrieve the exact voice and video call data (duration, start time, end time, hold time etc)?

The REST APIs that you linked to are going to give you the authoritative answer on the total duration of the Call or Room. We don't currently offer a Client side duration or start/end time but you could compute this yourself. For example:

```.swift
    var connectedDate: Date?
    var disconnectedDate: Date?

    func didConnect(to room: TVIRoom) {
        connectedDate = Date.init()
    }

    func room(_ room: TVIRoom, didDisconnectWithError error: Error?) {
        let now = Date.init()
        if let then = connectedDate {
            let duration = now.timeIntervalSince(then)
            print("Room duration was: \(duration) seconds.")
        }
        // Record for further use.
        disconnectedDate = now
    }
```

You could do something similar with our Voice SDK.

Best,
Chris

**Comment by newMobileStar** [comment]
@ceaglest  Thank you for your answer
Ok, I understand. I can try to do so.

Btw, I should save outgoing call duration on our server.
My question is

Is there a REST API to get child call sid from a parent call ?

**Comment by ceaglest** [comment]
Hi @newMobileStar,

> But for voice call, I cannot find out when the participant accepted the incoming call.
Is there any way for caller to know when the participant accepted the call ?

The mobile Voice SDKs don't currently fire events when the remote Participant accepts an incoming Call. This is something that the team is working on, but I don't have a definite timeline on when the feature will land.

Is there anything else I can help you with on this issue? (I believe you mentioned that your original problem was solved.)

Best,
Chris
