### ISSUE TITLE
[Feature Request] Allow developers to set contentScaleFactor for TVIVideoView

### ISSUE THREAD

**Issue by dineshflock** [twilio/video-quickstart-ios#272]
We allow our uses the zoom in the `TVIVideoView`.
For crisp zooming apple suggests to set `contentScaleFactor` on zoom did end.

Just to test, I tried recursively setting this factor to subviews of `TVIVideoView` and got crispy videos at the end of zooming as compared to videos where this was not set.

I would request an API on `TVIVideoView` to set scale factor for view doing the custom drawing.

Something like this 

```
TVIVideoView.h
-(void)setContentScaleFactorForMetalView:(CGFLoat)factor;

Something like this in TVIVideoView.m
-(void)setContentScaleFactorForMetalView:(CGFloat)factor {
  [_internalPrivateMetalView setScaleFactor:factor];
}
```

**Comment by vickprat** [comment]
Hey @ceaglest 
On behalf of @dineshflock, We are not setting CGAffineTransform instead we are using `scrollViewDidEndZooming:(UIScrollView *)scrollView withView:(UIView *)view atScale:(CGFloat)scale` and `(UIView *)viewForZoomingInScrollView:(UIScrollView *)scrollView method for zooming` and it was working on version 2.0.0-beta4 but now it is not working on version 2.1.0. Earlier we are doing the scaling thing on TVIMetalView which is not present in version 2.1.0. Video link for your reference https://developer.apple.com/videos/play/wwdc2011/104/

**Comment by ceaglest** [comment]
Hi @vickprat,

In 2.0.1+ we now use `MTKView` instead of our own `TVIMetalView`. What exactly isn't working for you in 2.1.0 (or 2.2.0)? Can you adjust your subview crawling to find `MTKView` instead? If so is the result different than before? There may be some additional automatic behavior in MTKView when it comes to content scale factors that was not present in previous releases.

Please let us know.

Best,
Chris

**Comment by muhammadsr** [comment]
That would be a very nice feature to have especially if we can pinch to zoom just like the app Zoom

**Comment by dineshflock** [comment]
@muhammadsr We CAN pinch and zoom. Twilio SDK provides a UIView and you can put that in a scroll view to get pinch and zoom. This is a feature request for another API.

**Comment by KurasovAnton** [comment]
Hi @stefanjudis, we are implementing pinch to zoom functionality in our app. We used same approach as described by @vickprat with UIScrollView. The issue is that the video is crisp and setting contentScaleFactor  for any subview of TVIViewView is not working.
Do you have any ideas on or best practices on how to remove TVIVideoView crisp video on zoom?

**Comment by ceaglest** [comment]
Hi @KurasovAnton,

> The issue is that the video is crisp and setting contentScaleFactor for any subview of TVIViewView is not working.

Just to confirm, did you actually find the child MTKView and set its contentScaleFactor directly? There are times when MTKView is going to automatically reset the contentScaleFactor to match the containing `UIWindow.screen.nativeScale`, so you might need to apply the change multiple times.

> Do you have any ideas on or best practices on how to remove TVIVideoView crisp video on zoom?

Besides crawling the view hierarchy you could make a UIScrollView with a contentSize that is a multiple of its bounds and then set the `minimumZoomScale` < 1. Allow the user to pinch in and the video should still be sharp. It would be better to set the contentScaleFactor properly though to avoid rendering extra pixels though.

Best,
Chris

**Comment by KurasovAnton** [comment]
@ceaglest, thank you for such a fast response.

> Just to confirm, did you actually find the child MTKView and set its contentScaleFactor directly?
Yes, I did. Also,  I've tested setting it for all child views of TVIViewView.
I set contentScalefactor to UIScreen.nativeScale * scale in scrollViewDidEndZooming.

> Besides crawling the view hierarchy you could make a UIScrollView with a contentSize that is a multiple of its bounds and then set the minimumZoomScale < 1. 

Good idea, thank you, but I suppose it would consume more phone resources, so I would like to find the solution with setting contentScaleFactor, if I could.

**Comment by KurasovAnton** [comment]
Hi @ceaglest , I've moved it from SrcollView and use CGAffineTransform and scaleFactor is working now.

**Comment by ceaglest** [comment]
Glad to hear it, and thanks for continuing to try out solutions. FWIW, I did notice a Github project which claims that MTKView and UIScrollView just do not work well together.

https://github.com/codelynx/Metal2DScrollable

If we do improve the `TVIVideoView.contentScaleFactor` setter in the future it will at least be possible to get the benefits by setting it outside of a UIScrollView.
