### ISSUE TITLE
ReplayKitExample: Content Sizing Error (-5807)

### ISSUE THREAD

**Issue by phukhanhlee** [twilio/video-quickstart-ios#322]
When I "Start Conference" - (ReplayKitExample/ViewController/func startConference()) . It shows error "Error Domain=com.apple.ReplayKit.RPRecordingErrorDomain Code=-5807 "Recording interrupted by multitasking and content resizing" UserInfo={NSLocalizedDescription=Recording interrupted by multitasking and content resizing})" . I saw this bug in another demo projects about record screen with ReplayKit.

"Start Broadcast" is working well !

iOS 12.0.1 -> may be this is problem ?
iPhone X -> may be this is problem ?

[solution] After I research -> here is the solution : just restart device and then it doesn't throw that error anymore.
https://stackoverflow.com/questions/51440249/replaykit-startcapturewithhandler-not-sending-cmsamplebufferref-of-video-type/52307215#52307215

**Comment by ceaglest** [comment]
Hello Developers,

There have been several bug reports filed (by Twilio, and other parties) against the iOS 12.x releases.

This Apple developer forum [thread](https://forums.developer.apple.com/thread/109696) offers a probable explanation of the cause of the error. Use Johnabre noticed:

> After looking at system logs more, like others my theory is that permissions popup is interfering with ReplayKit ^^;

A workaround may be possible, though ReplayKit doesn't seem to offer a standalone API to request screen capturing permissions. (You can ask for camera and microphone permissions in advance, if those are needed). We have cut ISDK-2539 to track this issue, and try workarounds.

Best,
Chris

**Comment by JulienLevallois** [comment]
I have the same error... with your test app ReplayKitExample,
Whats your solution ?

**Comment by piyushtank** [comment]
We think this is a bug in ReplayKit. We have reached out to apple and filed a radar for this.

**Comment by ceaglest** [comment]
Hi Developers,

This error should no longer occur on iOS 13 devices, and we have updated our [known issues](https://github.com/twilio/video-quickstart-ios/tree/master/ReplayKitExample#known-issues) section with this information.

If you are still able to reproduce on an iOS 13.x device, please let us know.

Thanks,
Chris

**Comment by Ankish** [comment]
I am able to replicate the same issue on iOS 14+
