### ISSUE TITLE
Setting TVICameraCapturer / TVIVideoCapturer Video Orientation

### ISSUE THREAD

**Issue by DanBlackwell** [twilio/video-quickstart-ios#324]
Hi, I have noticed that when screen rotation is enabled on an iOS device from which a stream is being sent, then the corresponding video track on a receiving device is also resized and rotated to match the orientation of the senders device when it changes. 

I assume that this is handled on the senders side (I'm guessing by the TVICameraCapturer); I'm wondering if I can manually set the orientation myself?

I would like to do this so that I can rotate the video stream to match the device orientation, despite my root ViewController only supporting portrait interface orientation (set by supportedInterfaceOrientations).

**Comment by ceaglest** [comment]
Hi @DanBlackwell,

Thank you very much for this feedback. 

> I would like to do this so that I can rotate the video stream to match the device orientation, despite my root ViewController only supporting portrait interface orientation (set by supportedInterfaceOrientations).

You are absolutely correct, TVICameraCapturer uses the interface orientation and not the device orientation to tag its video frames. Internally, the capturer can either monitor either the interface or device orientation. We never exposed the device orientation listener as an option, but we can if it suits your use case.

> I assume that this is handled on the senders side (I'm guessing by the TVICameraCapturer); I'm wondering if I can manually set the orientation myself?

Do you want to set the orientation manually, or would you be okay with us tracking UIDeviceOrientation?

Regards,
Chris

**Comment by ceaglest** [comment]
Hi Dan,

Excellent, I will keep this in mind. We are currently working on updated capture APIs and a new version of `TVICameraCapturer` so the feedback could not have come at a better time.

If you would be interested, we should have a preview release in the next few weeks with improvements in this area.

Regards,
Chris

**Comment by ceaglest** [comment]
Hi Dan,

We have recently shipped [2.6.0-preview1](https://www.twilio.com/docs/video/changelog-twilio-video-ios-version-2x#260-preview1-december-3-2018) which introduces `TVICameraSource` as a replacement to `TVICameraCapturer`. I did not have a chance to tackle improved orientation APIs for preview1, but this is planned for preview2.

I'll write on this ticket again once improved orientation APIs are available to try.

Thanks,
Chris

**Comment by DanBlackwell** [comment]
That sounds really promising, looking forward to seeing preview2 then!

Thanks,
Dan

**Comment by ceaglest** [comment]
Hi @DanBlackwell,

We have released [2.6.0-preview2](
https://www.twilio.com/docs/video/changelog-twilio-video-ios-version-2x#260-preview2-december-13-2018) with manual orientation controls for `TVICameraSource`. Unfortunately, since this is an advanced feature, we don't have sample code for it yet. However, it sounds like you have an app to try this out in already.

Best of luck, and do let us know if the APIs help with your use case.

Best,
Chris

**Comment by DanBlackwell** [comment]
Hi, just got around to building this into our apps; sorry for the big delay. I have to say it works great for our purpose. A quick note: I am setting the orientation off of the back of the UIDeviceOrientationDidChangeNotification and I have noticed that I need to set unexpected values for the camera orientation:

```
let newOrientation: TVIVideoOrientation
                switch device.orientation {
                case .portrait:
                    newOrientation = .left
                case .landscapeLeft:
                    newOrientation = .up
                case .landscapeRight:
                    newOrientation = .down
                case .portraitUpsideDown:
                    newOrientation = .right
                default:
                    return
                }
                self.camera?.update(newOrientation)
```

I'm not sure if this is expected, seems a little off to me.

Also, as a side note, is there a way to lock the video orientation of the `TVIVideoView` which I am using to preview the camera stream? Basically, whenever the device is rotated and I set the new orientation for the TVICameraSource, the preview autorotates so that the bottom of the video (ie the direction of gravity) is now oriented towards the bottom of the phone (ie towards the home button); if I am holding the device upside down, the preview appears upside down and landscape appears sideways relative to the world around me. On the receiving side the orientation is perfect, I just wish that I could lock the preview to being `.up`

**Comment by madhu-kadyala** [comment]
Hi,
I'm developing iOS video call app. In my case, I'm using Twilio -> 3.5 SDK. During a video call, If I rotate the device to landscape left my video is showing in landscape right direction. My video was 180 degrees wrong direction. I'm following the steps that was giving in video quick start in twilio. My app is not supported for landscape orientation.

**Comment by ceaglest** [comment]
Hey @madhu-kadyala,

Have you compared your app code to the QuickStart example? It supports rotating to portrait, landscape left, and landscape right on an iPhone. See also [Video Source APIs - Tracking Orientation Changes](https://www.twilio.com/docs/video/ios-v3-video-source-apis#tracking-orientation-changes) for more information.

Best,
Chris

**Comment by madhu-kadyala** [comment]
Hi @ceaglest 
I have followed the twilio video quick start code. But I'm facing this local video rotating issue in the landscape. 

let options = CameraSourceOptions { (builder) in
                // To support building with Xcode 10.x.
                #if XCODE_1100
                if #available(iOS 13.0, *) {
                    // Track UIWindowScene events for the key window's scene.
                    // The example app disables multi-window support in the .plist (see UIApplicationSceneManifestKey).
                    builder.orientationTracker = UserInterfaceTracker(scene: UIApplication.shared.keyWindow!.windowScene!)
                }
                #endif
            }
            camera = CameraSource(options: options, delegate: self)
            localVideoTrack = LocalVideoTrack(source: camera!, enabled: true, name: "Camera")

**Comment by ceaglest** [comment]
Hi @DanBlackwell,

> Hi, just got around to building this into our apps; sorry for the big delay.

That's okay, but now its me taking a long time to respond.

> A quick note: I am setting the orientation off of the back of the UIDeviceOrientationDidChangeNotification and I have noticed that I need to set unexpected values for the camera orientation:

It might seem unexpected, but the key information is that the natural orientation of the camera is `.landscapeLeft` and `.up` in our APIs indicates 0 degrees of rotation. I think we could do a better job of documenting working with the camera on iOS, some visuals to back up what I just said would be great.

> On the receiving side the orientation is perfect, I just wish that I could lock the preview to being .up

Yes, TVIVideoView is unfortunately trying to account for the orientation tags. I don't know if/when we would get a chance to deal with this. One thing you could do is wrap TVIVideoView in another renderer and then strip the tags by creating new TVIVideoFrames and feeding them in. Or you could also use TVICameraPreviewView and set the orientation manually.

Best,
Chris

**Comment by ceaglest** [comment]
Hey @madhu-kadyala,

Can you open another issue for the landscape problem? This issue was specifically about a manual orientation tracker API which shouldn't be needed in your case.

Since it has been a long time and we did ship these APIs in 2.6.0, I am going to close this issue out. Dan, feel free to re-open if you have more questions and are still working on a project using these APIs.

Cheers,
Chris
