### ISSUE TITLE
Audio on video chat is not working when play mobile video on video chat screen.

### ISSUE THREAD

**Issue by eldhosemathai** [twilio/video-quickstart-ios#338]
> Before filing an issue please check that the issue is not already addressed by the following:
>
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelog-twilio-video-ios-version-2x).
> 
> If this is an issue with the QuickStart itself, file it here. If this is an issue with the SDK or how to do something with the SDK please use [twilio-video-ios](https://github.com/twilio/twilio-video-ios/issues) instead.
>
> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description

[Description of the issue]

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. [Insert as many steps as needed]

#### Code

```swift
// Code that helps reproduce the issue
```

#### Expected Behavior

[What you expect to happen]

#### Actual Behavior

[What actually happens]

#### Reproduces How Often

[What percentage of the time does it reproduce?]

#### Logs

```
// Log output when the issue occurs
```

### Versions

All relevant version information for the issue.

#### Video iOS SDK

[e.g. 1.3.12 via CocoaPods]

#### Xcode

[e.g. 9.2]

#### iOS Version

[e.g. 11.2.6]

#### iOS Device

[e.g. iPhone 8 Plus]

**Comment by eldhosemathai** [comment]
I was trying to upload a video at the time of video chat on twilio. After uploading when i am trying to play the video in avplayerController, my audio of video chat gets stopped.

**Comment by paynerc** [comment]
@eldhosemathai,

Take a look at this [issue and comments](https://github.com/twilio/video-quickstart-objc/issues/62#issuecomment-447413167) filed in the [video-quickstart-objc](https://github.com/twilio/video-quickstart-objc) repo. It discusses mixing AVPlayer audio with Room audio and provides a link to a work in progress PR to attempt to solve the issue.

Please take a look at the linked issue and associated sample code and let me know if that gets you moving in the right direction.

Thank you,

Ryan

**Comment by paynerc** [comment]
@eldhosemathai,

It's been a while since we spoke. Checking in to see if the above information helped move your forward and if we can close out this ticket?

Thank you!

Ryan

**Comment by paynerc** [comment]
@eldhosemathai,

I am going to close this ticket. Feel free to reopen it if the suggestions above are not meeting your requirements.

Thank you,

Ryan
