### ISSUE TITLE
ARkit smooth switching between camera capture and ARKit scene 

### ISSUE THREAD

**Issue by nickoli58** [twilio/video-quickstart-ios#367]
### Description
Hello Twilio support. I’m looking for some clarification on the proper integration of ARKit in a video call.

Following the example, I am able to create a face tracking arkit session and send scene framEs using the displaylink with very good results. 

My question is, what is the best way to be able to switch between the regular camera capture and ARKit session as seamlessly as possible.  It seems I can’t change the source of a video track once it’s been created. Is that correct? The obvious solution is to use two separate tracks: A regular camera track and then one for the AR session and switch between them. 

The issue is, we would not like there to be any interruption/rebuffering when we begin the ARKit session and start sending frames with our scene nodes. Likewise when we end the ARKit session and want to go back to just the regular camera track. 

Any suggestions are greatly appreciated. Thank you!

**Comment by paynerc** [comment]
@nickoli58,

We have been discussing this internally and looking for an acceptable solution. One possibility is to use the ARKit/ARSession to capture video the whole time and just ignore the AR data when it's not wanted. However this might be quite expensive, but would require some testing to see the impact on battery and CPU usage.

You mentioned having two video tracks. Is it possible to start capture on both tracks, and toggle the enabled state between the two tracks. This way the tracks have been negotiated upon connecting to the room and in theory should reduce the interruption time you are trying to avoid.

Let me know if you have any further questions,

Ryan

**Comment by paynerc** [comment]
@nickoli58,

It's been a bit since we spoke last. Have you had any luck with the two possible solutions mentioned above?

Thanks,

Ryan

**Comment by paynerc** [comment]
@nickoli58,

I am going to close this ticket. Feel free to reopen it if the suggestions above are not meeting your requirements.

Thank you,

Ryan
