### ISSUE TITLE
Terminating app due to uncaught exception 'TVIAudioDeviceMustBeSetBeforeMediaStackSetup'

### ISSUE THREAD

**Issue by aksthelion** [twilio/video-quickstart-ios#371]
Twilio video version 2.6

When I start a video call, disconnect. Go back to VC, come back on video call view controller try to call again, I get following error with crash:

**Terminating app due to uncaught exception 'TVIAudioDeviceMustBeSetBeforeMediaStackSetup', reason: 'WebRTC does not allow updating the audio device once the media stack is created (i.e once a track is created or memory allocated for previously created room or connect option is not deleted). You should provide the audio device to SDK prior to creating the tracks.'**

I've checked this issue https://github.com/twilio/video-quickstart-swift/issues/230 but can't figure out what is the exact solution?

I've only one view controller in which I do all outgoing video call related operations. 

Can anyone explain to me how to fix this issue?

**Comment by ceaglest** [comment]
Hi @aksthelion,

If you're going to set the TVIAudioDevice, you need to do so only when no other Twilio Objects (Tracks, Rooms, Sources, Participants) are alive.

> I've only one view controller in which I do all outgoing video call related operations.

In this case could you set the device one time in viewDidLoad, or other initialization code that is only called once, and before other Twilio code?

Best,
Chris

**Comment by aksthelion** [comment]
It's already set in viewDidLoad. What do I need to check to make sure that I'm doing right thing? I think my problem is when I complete call, navigate away to another view and come back again to this view. It looks like all Twilio objects from previous calls are not cleared?

**Comment by aksthelion** [comment]
In sample code it's set in ViewController as shown below. This is the same code I've copied in my view controller where I show call control elements. Do we need to set it somewhere else such as AppDelegate?

`    override func viewDidLoad() {
        super.viewDidLoad()
        self.title = "QuickStart"

        /*
         * The important thing to remember when providing a TVIAudioDevice is that the device must be set
         * before performing any other actions with the SDK (such as creating Tracks, or connecting to a Room).
         * In this case we've already initialized our own `TVIDefaultAudioDevice` instance which we will now set.
         */
        TwilioVideo.audioDevice = self.audioDevice;
}`

**Comment by aksthelion** [comment]
This error happens when I click on connect immediately after previous call is disconnected. If I delay long enough for next click then this error doesn't occur. This indicates that Twilio objects are not getting deleted quickly? Or do I've to delete manually? Or do I've to wait for objects to be deleted before I present user option to navigate away? How do we fix this?

**Comment by ceaglest** [comment]
Hi @aksthelion,

> This error happens when I click on connect immediately after previous call is disconnected.

When you disconnect from the Room, you should wait for the -[TVIRoomDelegate room:didDisconnectWithError:] callback to complete (rather than nil'ing out the Room). Also, if you have a TVICameraSource, you should [stop the source](https://www.twilio.com/docs/video/video-source-apis#unpublishing-video-and-stopping-capture) as well.

Xcode's [memory graph debugger](https://medium.com/@imas145/using-memory-graph-debugger-in-xcode-9-a50aa9d0243f) can tell you if any Twilio objects are still alive, and which ones they are. Pay special attention to `TVIRoom` and `TVITrack` objects.

Best,
Chris

**Comment by aksthelion** [comment]
It's deleting for room:didDisconnectWithError. In my case error happens for participantDidDisconnect. Why you guys not deleting objects for participantDidDisconnect?

**Comment by piyushtank** [comment]
@aksthelion I work with @ceaglest on iOS Video SDK. 

Questions: Are you writing your own Custom audio device by implementing TVIAudioDevice protocol ? I wonder if you are not writing a custom audio device, you do not require to set audio device explicitly and SDK will take care of AudioDevice's life cycle itself.

As @ceaglest, have you run the memory graph right before `TwilioVideo.audioDevice = self.audioDevice;` is executed ? It should tell us if there is any Twilio objects were around when you call it.

**Comment by aksthelion** [comment]
I haven't written any custom code. I've just copied quickstart code. There is no custom anything. What is the solution you recommended in issue #230 which fixed this problem? Can you elaborate that solution in simple words?

**Comment by piyushtank** [comment]
@aksthelion Is it possible for you to share a branch with us where the problem can be reproduced? I feel we can come to a resolution faster that way.

**Comment by aksthelion** [comment]
It's a whole massive live app. Can I share my apps view controller file?

**Comment by piyushtank** [comment]
@aksthelion Is it possible for you to modify our quickstart sample app to reproduce the problem there?  If not, I will be happy to hop on a live screen sharing call with you to resolve the issue.
