### ISSUE TITLE
Video resolution dropping on high speed Wi-Fi with ReplayKit, but FPS staying the same.

### ISSUE THREAD

**Issue by cyoian** [twilio/video-quickstart-ios#404]
### Description

When we are on an in-office high speed Wi-Fi network, we are losing video resolution quality. Even if we drop the resolution down in-app to around 250px, the quality still seemingly drops. Is there something in WebRTC that is causing this resolution to drop even though we are on a high speed Wi-Fi connection?

We have implemented the most recent code from the ReplayKit example and the videoSink is successfully downscaling the resolution spatially now. The problem with the resolution dropping still persists even after we drop the resolution programatically.

Does the behavior we've described make sense to you, and if so, is there anything we can be doing to make sure that we deliver the best resolution possible? Thank you in advance for your time and expertise!

### Steps to Reproduce

1. Set the max resolution to be 1000px and maximum frames per second to 30.
3. Set downscaleBuffers to true
3. Start a conference (in-app)
4. Tune in

### Code
```swift
////////////// ViewController.swift //////////////
static let kMaxVideoBitrate = UInt(1400)
static let kDownScaledMaxWidthOrHeight = 1000
static let kDownscaleBuffers = true

if (DroneViewController.kDownscaleBuffers) {
	let outputFormat = ReplayKitVideoSource.formatRequestToDownscale(maxWidthOrHeight: DroneViewController.kDownScaledMaxWidthOrHeight)
	videoSource.requestOutputFormat(outputFormat)
}

////////////// ReplayKitVideoSource.swift //////////////
static let kDesiredFrameRate = 30

// Frame dropping logic.
if let lastTimestamp = lastTimestamp {
	let currentTimestamp = CMSampleBufferGetPresentationTimeStamp(sampleBuffer)
	let delta = CMTimeSubtract(currentTimestamp, lastTimestamp).seconds
	let threshold = Double(1.0 / Double(ReplayKitVideoSource.kDesiredFrameRate))

	if (delta < threshold) {
		return
	}
}

static func formatRequestToDownscale(maxWidthOrHeight: Int) -> TVIVideoFormat {
	let outputFormat = TVIVideoFormat()

	var screenSize = UIScreen.main.bounds.size
	screenSize.width *= UIScreen.main.nativeScale
	screenSize.height *= UIScreen.main.nativeScale

	let downscaledTarget = CGSize(width: maxWidthOrHeight,
								  height: maxWidthOrHeight)
	let fitRect = AVMakeRect(aspectRatio: screenSize,
							 insideRect: CGRect(origin: CGPoint.zero, size: downscaledTarget)).integral
	let outputSize = fitRect.size

	outputFormat.dimensions = CMVideoDimensions(width: Int32(outputSize.width), height: Int32(outputSize.height))
	return outputFormat;
}

func deliverFrame(sinkToFill: TVIVideoSink, timestamp: CMTime, buffer: CVPixelBuffer, orientation: TVIVideoOrientation, forceReschedule: Bool) {
	guard let frame = TVIVideoFrame(
		timestamp: timestamp,
		buffer: buffer,
		orientation: orientation
	) else {
		assertionFailure("We couldn't create a TVIVideoFrame with a valid CVPixelBuffer.")
		return
	}

	// sink gets the videoframe set here
	sinkToFill.onVideoFrame(frame)

	lastTimestamp = timestamp

	// Frame retransmission logic.
	if (ReplayKitVideoSource.retransmitLastFrame) {
		lastFrameStorage = frame
		lastTransmitTimestamp = CMClockGetTime(CMClockGetHostTimeClock())
		dispatchRetransmissions(forceReschedule: forceReschedule)
	}
}

func requestOutputFormat(_ outputFormat: TVIVideoFormat) {
	videoFormat = outputFormat

	if let sink = sink {
		sink.onVideoFormatRequest(outputFormat)
	}
}
```

#### Expected Behavior

The resolution should remain intact since there is a strong network connection and frames are seemingly still being sent through at the 30 fps we set.

#### Actual Behavior

The resolution drops until the video feed is very grainy.

#### Reproduces How Often

100%

#### Video iOS SDK

2.7

#### Xcode

10.2.1

#### iOS Version

12.3.1

#### iOS Device

iPad Mini 5th Generation

**Comment by paynerc** [comment]
@cyoian,

Thank you for reaching out. I spoke with another team member this morning and we are trying to understand why the resolution is dropping. For starters, it may be beneficial to try lowering the resolution of the frames being sent and/or increasing the bitrate. There may be an issue where it is unable to satisfy those constraints of the higher resolution and the lower bitrate.

A few asks to help us try and further debug this issue:

1. Could you provide some Room Sids where this is occurring?
2. Could you enable WebRTC `Info` logging and run the scenario again on the affected device? This would give us more insight into the downscaling that may be occurring. To enable to WebRTC logs, add the following to your code:
```
TwilioVideo.setLogLevel(.info, module: .webRTC)
```

When you have these, you can send them to support@twilio.com and reference this Github issue and mention that you are working with me and they will get directed my way.

Thank you!

Ryan

**Comment by cyoian** [comment]
@paynerc,

Thank you for your thorough response. We have tried raising the video bitrate and lowering resolution but it seems like we are still facing the same issue. We will enable WebRTC Info logging and run the scenario again. Here are our next debugging steps:

1. Enable WebRTC Info logging
2. Attempt raising video bitrate and dropping resolution in a few different configurations and check for better video quality
3. Copy logs and send them over to support@twilio.com with a reference to this GitHub issue

Thanks again Ryan!

**Comment by ceaglest** [comment]
Hello @cyoian,

I know that you and @paynerc have been communicating over a support ticket. I wanted to mention that after looking into some customer escalations regarding ReplayKit quality, I found that limiting the capture frame rate (especially when the content is complex app UIs, and not video) to greatly improve the experience under poor network conditions.

I will be working more on this PR next week: https://github.com/twilio/video-quickstart-ios/pull/408

Best,
Chris

**Comment by paynerc** [comment]
@cyoian,

I apologize for the delay in getting back to you on this issue. Is this still something you are having issues with? Have you taken a look a the PR which @ceaglest referred to above: #408? Does that help solve your issue?

Thank you,

Ryan

**Comment by paynerc** [comment]
@cyoian,

It's been awhile since we heard from you on this. I am going to close this issue but feel free to reopen if you are still experiencing the issue.

Ryan
