### ISSUE TITLE
Recording interrupted by multitasking and content resizing on ReplayKitExample

### ISSUE THREAD

**Issue by JulienLevallois** [twilio/video-quickstart-ios#405]
I got this error "Recording interrupted by multitasking and content resizing" when i launch ReplayKitExample.

Do you know why ?

Thanks

**Comment by piyushtank** [comment]
@JulienLevallois We think this is a bug in ReplayKit. We have reached out to apple and filed a radar for this.

This is a duplicate of https://github.com/twilio/video-quickstart-ios/issues/322. Can we close this ticket and track it at one place.

**Comment by ceaglest** [comment]
Closing as a duplicate. Please use #322 instead.
