### ISSUE TITLE
Playing audio track locally alongside active video call

### ISSUE THREAD

**Issue by jgadsby** [twilio/video-quickstart-ios#410]
Hi,

Is it possible to play some audio locally while the video call is active? For example, some background music that only the individuals can hear when both participants are using headphones?

Thanks!

**Comment by piyushtank** [comment]
@jgadsby It is possible to play audio locally only while in a video call. Our [AudioDevice example](https://github.com/twilio/video-quickstart-ios/tree/master/AudioDeviceExample) demonstrates the used case where user can play Audio from a file which gets played locally and on remote participant's phone. 

Let me know if you have any questions.

**Comment by jgadsby** [comment]
That's great, thank you!
