### ISSUE TITLE
[Question] CallKit - hand off to app after answering a call

### ISSUE THREAD

**Issue by jgadsby** [twilio/video-quickstart-ios#414]
This is hopefully a simple question with a simple solution. Using CallKit, is it possible to have the 'incoming call' screen provided by CallKit, and then upon the user answering the call, the app is launched and whatever custom video call UI is presented instead of using CallKit 'during the call'?

**Comment by paynerc** [comment]
Hey @jgadsby,

The behavior is dependent upon whether the phone was already unlocked when the incoming call was answered.

When the phone is unlocked and a call is answered from the CallKit UI, the application is automatically brought into the foreground and whatever UI your app presents will be displayed.

If the phone was locked and the call was answered, the native CallKit UI screen remains displayed, and there is a button in the lower right that, once tapped, will bring your application to the foreground (after providing the passcode or FaceID as necessary)

You can test this behavior out by running the VideoCallKitQuickStart application. Press the Simulate Incoming Call button, provide a room name and a delay. Once you press OK, leave the application but leave your phone unlocked. Answer the incoming call and you will see that it returns you to the application. Now try the same test but after pressing OK, leave the application and lock your phone. Upon answering the incoming call, you will see that you remain at the CallKit UI until pressing the `CallKit Quickstart` application button.

Let me know if you have any further questions,

Ryan

**Comment by jgadsby** [comment]
Gotcha. Is that an OS level limitation, or something I can work around?

**Comment by paynerc** [comment]
This is just how iOS works when you are on the locked phone screen. The user needs to take an action to unlock the device and go to the application.

**Comment by jgadsby** [comment]
Thanks! That's all I needed to know :)
