### ISSUE TITLE
Memory leak + CPU drain due to not calling stopCapture

### ISSUE THREAD

**Issue by kevinrenskers** [twilio/video-quickstart-ios#415]
When I look at https://github.com/twilio/video-quickstart-ios/blob/3.0.0-beta/VideoQuickStart/ViewController.swift, at no point is `camera?.stopCapture()` called, which results in unnecessary CPU usage and a memory leak when you move away from the video screen.

Of course in this quickstart application there is only the one screen, but in a normal app you would show and dismiss this screen, and not cleaning up the call causes problems. It would be nice if the quickstart examples deal with this, so it's obvious to everyone.

(In fact, I am seeing more memory problems even when I do correctly clean up the camera capture, as some `FigCaptureSourceVideoFormat` and `AVCaptureFigVideoDevice` objects are never released, but I guess that might be more of an SDK problem, rather than a quickstart problem?)

**Comment by ceaglest** [comment]
Our example apps have been updated to call `TVICameraSource.stopCapture()`. 

We are planning to improve the docs around TVICameraSource, and are considering adding automatic stopping behavior as an API improvement. I'm closing this issue since the sample apps were updated.
