### ISSUE TITLE
Override TVIVideoView class with ARSCNView

### ISSUE THREAD

**Issue by mongoose54** [twilio/video-quickstart-ios#416]
Hi ,

This might have been brought up in previous discussions here but I just wanted to see if it is feasible:

I would like to enable ARKit capabilities into the TVIVideoView. If this is possible are there any suggestions on how to enable that?

Thanks,
Alex

**Comment by paynerc** [comment]
@mongoose54 ,

Sorry for the very late response on this issue.

I am not sure I am following exactly what you are wanting to do. We do have an [ARKit example](https://github.com/twilio/video-quickstart-ios/tree/master/ARKitExample) that incorporates ARKit  to stream an augmented reality scene created with ARKit and SceneKit.

Does that sound like the use case that you are looking for, or is there something different that you can elaborate on a bit more?

Thank you,

Ryan

**Comment by paynerc** [comment]
This issue has been open for quite a while. Have you found a solution to your query?

Thank you, Ryan
