### ISSUE TITLE
Minimum deployment target for v. 3.x is unclear

### ISSUE THREAD

**Issue by andschdk** [twilio/video-quickstart-ios#437]
What is the minimum deployment target for version 3.x?

In docs it states iOS 10, while the podspec states iOS 11.
> 3.x removes support for iOS 9.0, and raises the minimum supported iOS version to 10.0. Twilio Video 2.x releases will continue to support iOS 9.0 and later.

https://www.twilio.com/docs/video/migrating-2x-3x-ios#ios-version-support

------------------------
**Podspec**
```
"platforms": {
    "ios": "11.0"
  }
```
https://github.com/CocoaPods/Specs/blob/master/Specs/1/d/9/TwilioVideo/3.0.0/TwilioVideo.podspec.json

**Comment by paynerc** [comment]
@andschdk,

Sorry about the confusion. The `podspec` is correct. The minimum iOS version that `3.0.0` supports is iOS 11. We typically support the most current iOS version and two versions prior. Since iOS 13 was released before `3.0.0` was GA'd, we also removed support for iOS 10, however it appears that we missed an update in the docs.

I am going to fix that doc issue right now. Sorry for any confusion that this has caused.

Ryan

**Comment by paynerc** [comment]
Actually, something else is amiss here. The document had been updated, but appears that it didn't publish properly. Looking into that and will report back when it is updated.

**Comment by paynerc** [comment]
@andschdk,

We are looking into the issue with the docs not being published correctly, however we forced the update of the migration guide.

If you take a look now, you will see the [Xcode and iOS Version Support](https://www.twilio.com/docs/video/migrating-2x-3x-ios#xcode-and-ios-version-support) section now shows appropriately.

I apologize for the inconvenience that this has caused. Please let me know if you have any further questions or issues and if we can close out this issue.

Thank you,

Ryan

**Comment by andschdk** [comment]
Thank you for your quick reply and clarification 👍

**Comment by paynerc** [comment]
Follow up: The source of the publishing issue has been addressed. I have validated that all the [iOS Programmable Video docs](https://www.twilio.com/docs/video) have been properly published and are up to date for the `3.0.0` release.

Again, apologies for any confusion that may have arisen.

Ryan
