### ISSUE TITLE
How to remove local and remote data track? (Like eraser functionality)

### ISSUE THREAD

**Issue by RahulDhiman93** [twilio/video-quickstart-ios#439]
@IBAction func eraseButtonTapped(_ sender: UIButton) {
        for (_, drawer) in self.drawers {
            drawer.shapeLayer!.removeFromSuperlayer()
        }
        self.drawers.removeAll(keepingCapacity: true)
        self.localParticipant = nil
        
    }

As this code remove drawer from superLayer but when I try to draw again It will crash the app. 

@IBAction func eraseButtonTapped(_ sender: UIButton) {
        for (_, drawer) in self.drawers {
            drawer.shapeLayer!.removeFromSuperlayer()
        }
    }

Only this code remove drawer from superLayer but again I try to draw it will pop back again.

**Comment by piyushtank** [comment]
@RahulDhiman93 Apologies for the late response. Drawing on a layer is UIKit specific question, it's not video sdk specific issue. I would be happy to look at the code to help if you share a branch if the problem hasn't fixed yet.

**Comment by piyushtank** [comment]
Closing this ticket but feel free to re-open or post another ticket if you have any issue.
