### ISSUE TITLE
Using RemoteIO with microphone

### ISSUE THREAD

**Issue by snobear** [twilio/video-quickstart-ios#444]
Hi, 
When playing instruments over TwilioVideo, the voice processing seems to degrade the quality of instruments like guitar and piano pretty badly. From what I understand, RemoteIO in CoreAudio is a possible solution to disable the extra processing thats happening.  Our app users will be playing one at a time, so we're not concerned with cancelling echo from additional participants.
 
I was checking out https://github.com/twilio/video-quickstart-ios/tree/master/AudioDeviceExample as it uses RemoteIO, but I see its only for audio file playback and not microphone. Is there an example of the same, but for use with the built-in mic or any thoughts or concerns around doing this?

**Comment by ceaglest** [comment]
Hey @snobear,

> Is there an example of the same, but for use with the built-in mic or any thoughts or concerns around doing this?

We don't have this exact use case covered in example code, but if you're looking to use RemoteIO in place of VoiceProcessingIO, you could take ExampleCoreAudioDevice and modify it. You would need to:

1. Enable the input bus for the RemoteIO audio unit. The flag is [here](https://github.com/twilio/video-quickstart-ios/blob/b74e1c1c4f49ae23f326bd3e53ec750f126d5b2d/AudioDeviceExample/AudioDevices/ExampleCoreAudioDevice.m#L300).
2. Add a rendering callback for the input bus. Like this [example](https://github.com/twilio/video-quickstart-ios/blob/b74e1c1c4f49ae23f326bd3e53ec750f126d5b2d/AudioDeviceExample/AudioDevices/ExampleAVAudioEngineDevice.m#L675) but without the extra mixing logic that you don't need.
3. Implement `TVIAudioDeviceCapturer` methods to claim support for capturing.

I hope this is helpful, but I understand that what I just described is pretty low level and might be difficult depending on your knowledge of real time audio.

Best,
Chris

**Comment by snobear** [comment]
Hi @ceaglest, thanks for the reply and the info. Audio programming is certainly not in my wheelhouse, but I'll take a crack at it nonetheless. I may come back with a question or two :).

**Comment by ceaglest** [comment]
Thanks! Let us know if you have any more questions.
