### ISSUE TITLE
Support for macOS

### ISSUE THREAD

**Issue by jchand** [twilio/video-quickstart-ios#447]
Wondering if anyone has had success using this library for native macOS applications? I realize this is specifically for iOS, but curious if the Catalyst cross-platform efforts have enabled this.

**Comment by ceaglest** [comment]
Hi @jchand,

Thanks for asking. We don't offer support for Catalyst, but our 3.0 SDK is built using Xcode 11 which enables support for Catalyst apps and frameworks.

We are tracking the feature request here: https://github.com/twilio/twilio-video-ios/issues/49

Best,
Chris

**Comment by ceaglest** [comment]
Lets track this request in the twilio-video-ios issue that I linked. Have a good day!
