### ISSUE TITLE
ReplayKit broadcast extension : Getting Undefined symbols for architecture x86_64:   "_ExampleCoreAudioDeviceGetCurrentQueue", referenced from:       ScreenShare.ReplayKitVideoSource.processFrame(sampleBuffer: __C.CMSampleBufferRef) -> () in ReplayKitVideoSource.o ld: symbol(s) not found for architecture x86_64 clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by Zindal** [twilio/video-quickstart-ios#451]
> Before filing an issue please check that the issue is not already addressed by the following:
>
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelog-twilio-video-ios-version-2x).
> 
> If this is an issue with the QuickStart itself, file it here. If this is an issue with the SDK or how to do something with the SDK please use [twilio-video-ios](https://github.com/twilio/twilio-video-ios/issues) instead.
>
> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description

[Description of the issue]

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. [Insert as many steps as needed]

#### Code

```swift
// Code that helps reproduce the issue
```

#### Expected Behavior

[What you expect to happen]

#### Actual Behavior

[What actually happens]

#### Reproduces How Often

[What percentage of the time does it reproduce?]

#### Logs

```
// Log output when the issue occurs
```

### Versions

All relevant version information for the issue.

#### Video iOS SDK

[e.g. 1.3.12 via CocoaPods]

#### Xcode

[e.g. 9.2]

#### iOS Version

[e.g. 11.2.6]

#### iOS Device

[e.g. iPhone 8 Plus]

**Comment by paynerc** [comment]
@Zindal,

Would you be able to provide some context as to the issue you raised? The issue template that we provide (above) helps us to determine the nature of the issue, reproduction steps, etc.

I'm guessing you received this issue when building the ReplayKit example for an iOS Simulator. But I don't know what version of Xcode you are using, what OS version you are targeting for the simulator, what version of the TwilioVideo SDK the example is consuming.

I have build the ReplayKit example app using Xcode 11.3.1, targeting an iPhone 8 simulator running iOS 13.3, consuming Twilio Video 3.1.0 and did not get this issue.

Let me know the details of how you got this error and we can then work on figuring out the resolution.

Thanks,

Ryan

**Comment by Zindal** [comment]
**Description :** 

ReplayKit broadcast extension : Getting Undefined symbols for architecture x86_64: "_ExampleCoreAudioDeviceGetCurrentQueue", referenced from: ScreenShare.ReplayKitVideoSource.processFrame(sampleBuffer: __C.CMSampleBufferRef) -> () in ReplayKitVideoSource.o ld: symbol(s) not found for architecture x86_64 clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Steps to Reproduce**

1. Download the Twilio replaykit source code
2. Creat new project with all files.
3. Compiler show below error
4. Undefined symbols for architecture x86_64: "_ExampleCoreAudioDeviceGetCurrentQueue", referenced from: ScreenShare.ReplayKitVideoSource.processFrame(sampleBuffer: __C.CMSampleBufferRef) -> () in ReplayKitVideoSource.o ld: symbol(s) not found for architecture x86_64 clang: error: linker command failed with exit code 1 (use -v to see invocation)


**Code**
According error, it is because of below code in  file "ExampleReplayKitAudioCapturerDispatch.h"
`dispatch_queue_t ExampleCoreAudioDeviceGetCurrentQueue(void);`

**Expected Behaviour** 
It should Run the without any error, because the sample code that i have downloaded it is working. But when i create new project with all files it is showing error. 

**Video iOS SDK**
pod 'TwilioVideo', '~> 3.0'

Same version of twilio video SDK the sample code has and it is working.

**Xcode**
Xcode 11.1

**iOS Version**
Deployment Target : IOS 12
Device IOS Version : IOS 12.4.4
Device : iPhone 6

**Comment by paynerc** [comment]
It would be helpful to see your project configuration. Do you have `ExampleReplayKitAudioCapturer.m` included in the project and set to build for your target? The linker error makes me believe that while you have the header file, the linker cannot find the built objects at link time.

**Comment by Zindal** [comment]
Hello

Thank you for your reply, I have added that file but it did not work, what
works is I deleted the entire extension thing and then create it again. And
it working fine now. Do not know how but right now working.

Thank you for you reply again..

**Comment by paynerc** [comment]
@Zindal,

I’m glad to hear you got it resolved. Let me know if you have any further questions.

Ryan

**Comment by jeeva-sil** [comment]
@paynerc 

I am facing this issue. 

`Undefined symbols for architecture arm64:
  "_ExampleCoreAudioDeviceGetCurrentQueue", referenced from:
      KeepFluent.ReplayKitVideoSource.processFrame(sampleBuffer: __C.CMSampleBufferRef) -> () in ReplayKitVideoSource.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by Nishant9SPL** [comment]
Hello,

I am facing the below error while integrating the TwilioReplyKit Extension:
ReplayKit broadcast extension : Getting Undefined symbols for architecture x86_64: "_ExampleCoreAudioDeviceGetCurrentQueue", referenced from: ScreenShare.ReplayKitVideoSource.processFrame(sampleBuffer: __C.CMSampleBufferRef) -> () in ReplayKitVideoSource.o ld: symbol(s) not found for architecture x86_64 clang: error: linker command failed with exit code 1 (use -v to see invocation) 

As per the above solution, I have tried with removing the broadcast extension and recreate it. But not successed.

To further update, below is the steps I followed:

1) Added "ReplayKitVideoSource.swift" file into my main project.
2) Created Broadcast Extension and added Twilio Pod. (Extension name is "BroadcastExtension"
3) I have added POD as below:

target '<Project Name>' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for <Project Name>
    
   pod 'TwilioVideo', '~> 3.6'
end

target 'BroadcastExtension' do
  use_frameworks!
  pod 'TwilioVideo', '~> 3.6'
end


But after adding the pods, it is giving error for the file "ReplayKitVideoSource.swift". If I remove this file, the project successfully compiled. But when I am adding this file, facing the above issue.

Please let me know for that.

**Comment by paynerc** [comment]
@Nishant9SPL,

`ReplayKitVideoSource.swift` currently has a dependency on the `ExampleReplayKitAudioCapturer` Objective-C files that are in the [`BroadcastExtension`](https://github.com/twilio/video-quickstart-ios/tree/master/ReplayKitExample/BroadcastExtension) folder of the ReplayKit example. This is referenced [here](https://github.com/twilio/video-quickstart-ios/blob/b74e1c1c4f49ae23f326bd3e53ec750f126d5b2d/ReplayKitExample/ReplayKitExample/ReplayKitVideoSource.swift#L209).

If you are integrating the example code into your application, you would also need to be sure to add the files in the BroadcastExtension folder as mentioned [above](https://github.com/twilio/video-quickstart-ios/issues/451#issuecomment-582429028).

Ryan

**Comment by Nishant9SPL** [comment]
@paynerc 

Yes, I have already added "ExampleReplayKitAudioCapturer.h" and "ExampleReplayKitAudioCapturer.m". 
Also,  added Bridging Header file into extension as well.

Then also it is giving the same error.

-- Nishant
