### ISSUE TITLE
AudioDeviceExample has wrong sample rate when played through airpods

### ISSUE THREAD

**Issue by luoser** [twilio/video-quickstart-ios#456]
### Description

Listening to the music through Airpods causes the music to play back at a slow rate (track sounds darker, distorted, and slower, very different than input file).

### Steps to Reproduce

1. Select AVAudioEngineDevice and connect to room with device connected to airpods
1. Tap `Music`
1. Audio playback is distorted

#### Expected Behavior

Audio playback sounds the same on all routes.

#### Actual Behavior

Audio playback through BluetoothHFP has much slower sample rate (16hz vs 44-48hz).

#### Reproduces How Often

100%

### Versions

All relevant version information for the issue.

#### Video iOS SDK

3.0.1

#### Xcode

11.3.1

#### iOS Version

13

#### iOS Device

iPhone X

**Comment by paynerc** [comment]
@luoser ,

Thanks for reporting this issue. I will attempt to reproduce this issue and see what we can do about it.

Thank you,

Ryan

**Comment by paynerc** [comment]
Sorry for the delay in looking into this. I can confirm that I am able to reproduce this locally with a pair of Powerbeats. 

I am going to investigate and see what we can do about it. I will keep you posted.

Ryan

**Comment by piyushtank** [comment]
Hi @luoser 

Thanks for filing the ticket. I have just created a pull request which fixes this issue - https://github.com/twilio/video-quickstart-ios/pull/464. 

Try it out and feel free to post feedbacks on the pull request.

Best,
Piyush

**Comment by luoser** [comment]
Awesome! will take a look this evening. thanks for addressing the issue

**Comment by piyushtank** [comment]
Closing the ticket as we have fixed the issue in our quickstart. Feel free to re-open if you run into the issue.
