### ISSUE TITLE
Twilio:: AVAudioSession setActive Error Domain=NSOSStatusErrorDomain Code=561017449

### ISSUE THREAD

**Issue by ghanshyam-mi** [twilio/video-quickstart-ios#457]
We have migrated Twilio Video SDK from 2.x to 3.x.There is an issue related to audio in the video call. I can see the remote participants but can't hear them.

I had a test on multiple devices that are running on iOS 12 and iOS 13. I am still fetching the same issue on these devices. 

It looks like there is an issue in TwilioVideo 3.2.2 version. If I remove CallKit for video call then it working fine. 

#### Logs

2020-02-29 14:48:12.821190+0530 XXXXXXXX[11992:2162580] ERROR:Twilio:[Platform](0x105959800): AVAudioSession setActive Error Domain=NSOSStatusErrorDomain Code=561017449 "(null)"

Fail: The operation couldn’t be completed. (OSStatus error 561017449.)
Fail: The operation couldn’t be completed. (OSStatus error 561017449.)
Fail: The operation couldn’t be completed. (OSStatus error 561017449.)

Twilio:[Platform](): AVAudioSession setActive Error Domain=NSOSStatusErrorDomain Code=561017449 "(null)"

[aurioc] 1029: failed: '!pri' (enable 3, outf< 1 ch,  44100 Hz, Int16> inf< 1 ch,  44100 Hz, Int16>)
[aurioc] AURemoteIO.cpp:1086:Initialize: failed: 561017449 (enable 3, outf< 1 ch,  44100 Hz, Int16> inf< 1 ch,  44100 Hz, Int16>

### Versions

All relevant version information for the issue.

#### Video iOS SDK
- TwilioVideo (3.2.2)

#### Xcode
11.3.1

#### iOS Version
12.x and 13.3.1

#### iOS Device
iPhone 6s, iPhone 7, iPhone 8, iPhone X

**Comment by paynerc** [comment]
@ghanshyam-mi ,

I will attempt to reproduce and see what we need to do to get this working.

Have you tried this on other 3.x releases? Is it just a problem with 3.2.2 or with any of the 3.x releases.

Are you using the CallKit sample app to reproduce this or is this in your own application?

Thank you,

Ryan

**Comment by shahzaibiqbal** [comment]
I am also facing same issue. I tried 3.2.2 and 3.2.1. For me its happening when i receiver a cellular call during video call and if caller end the cellular call i get the same error but if i end the cellular call it works fine. Other thing is when this scenario happen `CXProviderDelegate` method `func provider(_ provider: CXProvider, didActivate audioSession: AVAudioSession)` called instead of that `func provider(_ provider: CXProvider, didDeactivate audioSession: AVAudioSession)` get called. Any help would be greatly appreciated. Thank you.

**Comment by kiran4991** [comment]
I am also facing the same issue

**Comment by piyushtank** [comment]
Hi @ghanshyam-mi @kiran4991 @shahzaibiqbal - 

Since CallKit activates the AVAudioSession, it is very important to use TwilioVideo SDK's audio API appropriately while using CallKit to avoid errors.

Have you tried using our [CallKit Quickstart](https://github.com/twilio/video-quickstart-ios/tree/master/VideoCallKitQuickStart.xcodeproj)? The [CallKit Quickstart](https://github.com/twilio/video-quickstart-ios/tree/master/VideoCallKitQuickStart.xcodeproj) demonstrates how to use TwilioVideo SDK's audio apis with CallKit. I tried outgoing and simulated incoming call scenario using the call kit quickstart sample app with TwilioVideo 3.2.2 SDK, and it worked as expected.

Let me know if you have any questions.

Best,
Piyush

**Comment by shahzaibiqbal** [comment]
@piyushtank Yes, i have looked in to mentioned repo and that where i am facing same problem. For some reason call kit delegate `func provider(_ provider: CXProvider, didActivate audioSession: AVAudioSession)` dnt get fired when the other caller end the call.

**Comment by piyushtank** [comment]
@shahzaibiqbal Are you able to reproduce the bug on CallKit Quickstart? If yes, can you provide the exact steps to reproduce the bug on [CallKit Quickstart](https://github.com/twilio/video-quickstart-ios/tree/master/VideoCallKitQuickStart.xcodeproj) sample app?

**Comment by shahzaibiqbal** [comment]
@piyushtank. I was able to produce it last time when i tested it couple of days ago. Now when i try to run [CallKit Quickstart](https://github.com/twilio/video-quickstart-ios/tree/master/VideoCallKitQuickStart.xcodeproj) app is crashing. I am using ccode Version 11.4 (11E146). Here are steps which was giving me troubles. You can try them. 

1. Install app and place a video call and make sure both sides are on call. (in my case i am calling from my iPhone(let call this device ip1) to simulator using same project).
2. Now make a Facetime audio or cellular call from some other device (let call this device ip2)to iPhone(ip1).
3. Choose hold and accept option. (right now on this step app is crashing for me on my current version of  xcode)
4. Now hang up the call from ip2. 
These are the steps. If i hang up call from ip1 its work fine but not from ip2.
Thanks.

**Comment by piyushtank** [comment]
@shahzaibiqbal I tried to reproduce the issue following the steps ^ using the CallKit Quickstart app. I could not see any problem, the app worked as expected. I have uploaded the video file [here](https://drive.google.com/open?id=1JgF-1y7mlAHxGWU-p6_iRash_QTUpzV_).



.

**Comment by shahzaibiqbal** [comment]
@piyushtank  Thanks for looking in to it. I am able to solve the issue by add following code in to delegate method ` func provider(_ provider: CXProvider, didDeactivate audioSession: AVAudioSession)`. I dnt know why i am getting issue but doing following resolve the issue for me. 
`let cxObserver = callKitCallController.callObserver
        let calls = cxObserver.calls
        guard let call = calls.first(where:{$0.uuid == self.room?.uuid}) else {

            return
        }
        if calls.count == 1 && call.isOnHold {
            let holdAction = CXSetHeldCallAction(call: call.uuid, onHold: false)
            let transaction = CXTransaction(action: holdAction)
            self.callKitCallController.request(transaction) { (error) in
                if let actionError = error {
                    self.logMessage(messageText: "provider:didDeactivateAudioSession: Setting action error " + actionError.localizedDescription)
                }
                
            }
        }`

**Comment by piyushtank** [comment]
@shahzaibiqbal Thanks for the note.

**Comment by chathurka** [comment]
Please consider following function because I had this issue and fixed the issue.

func provider(_ provider: CXProvider, perform action: CXSetHeldCallAction) {
        if (action.isOnHold) {
            stopAudio() // AVAudioSession.sharedInstance().setActive(false)
        } else {
            startAudio() // AVAudioSession.sharedInstance().setActive(true)
        }
        action.fulfill()
}

**Comment by gsbernstein** [comment]
@chathurka that did it!
