### ISSUE TITLE
How to make the remote video view fill the entire view

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [twilio/video-quickstart-ios#463]
### Description

I managed to get the video chat set up with the help of the Quick start code samples. I used the same code from the sample to layout the remote video view. 

I want it to be portrait and fill the entire view. But what I get looks like this.

![rsz_img_2354-2](https://user-images.githubusercontent.com/2551877/77455359-bfda0780-6e1f-11ea-8c12-4181fc64038e.png)

Remote video view does not fill the entire view

#### Code

```swift
private func setupRemoteVideoView() {
    // Creating `VideoView` programmatically
    remoteVideoView = VideoView(frame: CGRect.zero, delegate: self)
    remoteVideoView?.contentMode = .scaleAspectFit
    view.insertSubview(remoteVideoView!, at: 0)

    let centerX = NSLayoutConstraint(item: remoteVideoView!, attribute: NSLayoutConstraint.Attribute.centerX, relatedBy: NSLayoutConstraint.Relation.equal, toItem: view, attribute: NSLayoutConstraint.Attribute.centerX, multiplier: 1, constant: 0);
    view.addConstraint(centerX)
    let centerY = NSLayoutConstraint(item: remoteVideoView!, attribute: NSLayoutConstraint.Attribute.centerY, relatedBy: NSLayoutConstraint.Relation.equal, toItem: view, attribute: NSLayoutConstraint.Attribute.centerY, multiplier: 1, constant: 0);
    view.addConstraint(centerY)
    let width = NSLayoutConstraint(item: remoteVideoView!, attribute: NSLayoutConstraint.Attribute.width, relatedBy: NSLayoutConstraint.Relation.equal, toItem: view, attribute: NSLayoutConstraint.Attribute.width, multiplier: 1, constant: 0);
    view.addConstraint(width)
    let height = NSLayoutConstraint(item: remoteVideoView!, attribute: NSLayoutConstraint.Attribute.height, relatedBy: NSLayoutConstraint.Relation.equal, toItem: view, attribute: NSLayoutConstraint.Attribute.height, multiplier: 1, constant: 0);
    view.addConstraint(height)
}
```

#### Expected Behavior

The remote video view to fill the entire view.

#### Actual Behavior

Remote video view does not fill the entire view.

#### Reproduces How Often

100%

#### Video iOS SDK

3.2.2 via CocoaPods

#### Xcode

11.3

#### iOS Version

13.3.1

#### iOS Device

iPhone 11 Pro

**Comment by ceaglest** [comment]
Hi @Isuru-Nanayakkara,

From your screenshot, it looks like the remote party has their device in landscape. If both are iOS devices, holding them in the same orientation will result video that fills more, but not all of the screen. If you just want to crop the video to fill the screen then you can use UIViewContentModeScaleAspectFill.

```.swift
remoteVideoView?.contentMode = .scaleAspectFill
```

It is also possible to use TVICameraSource to choose a 16:9 format that will be closer to filling the screen when the orientation of each device is the same. See [Selecting a Device Format](https://www.twilio.com/docs/video/ios-v3-video-source-apis#selecting-a-device-format) in our guide, and also the [MultiPartyExample](https://github.com/twilio/video-quickstart-ios/tree/master/MultiPartyExample) for some pointers.

Let me know if you need any more help.

Thanks,
Chris

**Comment by Isuru-Nanayakkara** [comment]
Hi @ceaglest, thanks for the help. Setting the content mode to `. scaleAspectFill` indeed did the trick.

If I were to go with the `TVICameraSource` route, I'll have to check the orientation and device types dynamically to choose the best format, right?

**Comment by ceaglest** [comment]
Hey @Isuru-Nanayakkara,

That's good to hear.

> If I were to go with the TVICameraSource route, I'll have to check the orientation and device types dynamically to choose the best format, right?

Yes that is correct. For example, if one device is an iPad then the default format (640x480) will already fill the screen in most cases.

Best,
Chris

**Comment by Isuru-Nanayakkara** [comment]
I see. I think `remoteVideoView?.contentMode = .scaleAspectFill` fits my needs fine for now. Thanks for the help!

**Comment by cyrilzakka** [comment]
Sorry to reopen this, but in my case, the remote view is sideways despite both devices being in the same orientation. Any ideas?

Here's how I capture the frames:
```
 @objc func displayLinkDidFire(timer: CADisplayLink) {
        self.arView.snapshot(saveToHDR: false) { (image) in
            let compressedImage = UIImage(data: (image?.pngData())!)
            self.frame = VideoFrame(timeInterval: timer.timestamp,
                                    buffer: (compressedImage?.convertToBuffer())!,
                                    orientation: VideoOrientation.left)
            self.sink!.onVideoFrame(self.frame!)
        }
    }
```

and
`remoteVideoView?.contentMode = .scaleAspectFill`.
