### ISSUE TITLE
Twilio:: AVAudioSession setActive Error Domain=NSOSStatusErrorDomain Code=561017449

### ISSUE THREAD

**Issue by kiran4991** [twilio/video-quickstart-ios#467]
I am using cocoapod pod 'TwilioVideo', '~> 3.0.1', when I receive  a call from callkit , audio is not working... I can able to see a video , but not able to hear an audio.. I tried 

do {
            try AVAudioSession.sharedInstance().setCategory(AVAudioSession.Category.playAndRecord, mode: AVAudioSession.Mode.videoChat, options: .mixWithOthers)
            try AVAudioSession.sharedInstance().setActive(true,options: .notifyOthersOnDeactivation)
            try AVAudioSession.sharedInstance().setActive(true)
        } catch {
            print("Speaker error : \(error)")
        }
      
            self.provider?.reportNewIncomingCall(with: uuid, update: update, completion: { (error) in}
this solution also but no luck..

Logs
2020-02-29 14:48:12.821190+0530 XXXXXXXX[11992:2162580] ERROR:Twilio:Platform: AVAudioSession setActive Error Domain=NSOSStatusErrorDomain Code=561017449 "(null)"

[aurioc] 1029: failed: '!pri' (enable 3, outf< 1 ch,  44100 Hz, Int16> inf< 1 ch,  44100 Hz, Int16>)

Twilio:Platform: AVAudioSession setActive Error Domain=NSOSStatusErrorDomain Code=561017449 "(null)"

[aurioc] 1029: failed: '!pri' (enable 3, outf< 1 ch, 44100 Hz, Int16> inf< 1 ch, 44100 Hz, Int16>)
[aurioc] AURemoteIO.cpp:1086:Initialize: failed: 561017449 (enable 3, outf< 1 ch, 44100 Hz, Int16> inf< 1 ch, 44100 Hz, Int16>

Versions
All relevant version information for the issue.

Video iOS SDK
TwilioVideo (3.0.1)
Xcode
11.0

iOS Version
13.3.1

iOS Device
iPhone 6s, iPhone 7, iPhone 8, iPhone X

**Comment by ceaglest** [comment]
Hi @kiran4991,

This issue is already being tracked in #457, and I saw you responded on that ticket. Lets keep the discussion in one place.

Thanks,
Chris
