### ISSUE TITLE
Audio does not continue to route through AirPods after resuming the app.

### ISSUE THREAD

**Issue by jgadsby** [twilio/video-quickstart-ios#468]
### Description
See the title.

### Steps to Reproduce

1. Create a room and join it with other participants.
2. Put your paired AirPods / bluetooth headphones on
3. Observe how the audio continues to come out of the speakers, not the AirPods.

#### Code
(Used the sample code)

#### Expected Behavior
Connecting AirPods during a conversation should automatically route the audio through them.

#### Actual Behavior
Connecting AirPods does not make a difference to the original audio source. Attempting to change the 'audioDevice' midway through a call causes a crash.

#### Reproduces How Often
All the time.

#### Video iOS SDK
The latest SDK

#### Xcode
The latest XCode

#### iOS Version
Any

#### iOS Device
Any

**Comment by piyushtank** [comment]
@jgadsby Thanks for reaching out.

I just tried the scenario using our [Quickstart sample app](https://github.com/twilio/video-quickstart-ios/tree/master/VideoQuickStart). It works as expected - the call established without air pods on, the audio was routing to speaker, and when used the air pods, audio was routing to air pods. I tried back and forth few times with and without air pods on, the audio route worked correctly.

Let me know if you have any questions.

Best,
Piyush

**Comment by jgadsby** [comment]
@piyushtank do I need to do anything like this before the video chat starts? If I leave it out, AirPods don't work at all:                    

TwilioVideoSDK.audioDevice = DefaultAudioDevice()

**Comment by piyushtank** [comment]
@jgadsby  You should not require to set `TwilioVideoSDK.audioDevice` in your app if you are using the DefaultAudioDevice. 

Have you tried the Quickstart sample app? I recommend trying it out first, and then compare the code.

**Comment by jgadsby** [comment]
I think I figured it out - I wasn't setting the Opus Audio codec?

**Comment by jgadsby** [comment]
@piyushtank I can actually reproduce this issue again. It happens when I leave the app and come back to it. AirPods will stop working and are unable to connect again after returning to the app from a paused state.

**Comment by jgadsby** [comment]
@piyushtank or @ceaglest Do either of you have any ideas why AirPods might stop working upon pausing the app?

**Comment by ceaglest** [comment]
@jgadsby is this in the AudioDeviceExample or your own app? If its your own app do you have background audio permissions?

**Comment by jgadsby** [comment]
Never mind, it was an error in our own app. We have some code to re-init the audio capture session when the app is resumed, like so: 

`        // Fix issue where audio capture is disabled when returning from background, if you're in a room
        if self.room != nil {
            do {
                try AVAudioSession.sharedInstance().setCategory(
                    .playAndRecord, mode: .videoChat,
                    options: [.mixWithOthers,
                              .allowAirPlay,
                              .allowBluetoothA2DP,
                              .allowBluetooth])
                try AVAudioSession.sharedInstance().setActive(true)
            } catch {
                logMessage(messageText: "Audio error : \(error)")
            }
`

We just needed to add Bluetooth support here in the options array.
