### ISSUE TITLE
Add Video Renderer is taking a lot of time

### ISSUE THREAD

**Issue by Balasnest** [twilio/video-quickstart-ios#470]
### Description

After subscribed to video track for Participant, it's taking **~8 sec** to render the remote view. so participants are seeing blank for a while till video render.
### Steps to Reproduce

2020-04-04 23:31:48.688685+0530 app[3123:7123] TwilioVideo v2.5.6
2020-04-04 23:31:48.695912+0530 app[3123:7123] Video track created
2020-04-04 23:31:48.742783+0530 app[3123:7123] Attempting to connect to room 5****
2020-04-04 23:31:51.414847+0530 app[3123:7123] Connected to room 5**** as 5****
2020-04-04 23:31:51.902125+0530 app[3123:7123] Subscribed to audio track for Participant 5****
2020-04-04 23:31:51.902775+0530 app[3285:792734] Subscribed to video track for Participant 5**** (At this stage, remote video is not showing, from here its taking ~3-8 sec taking) 

#### Code

```
- (void)subscribedToVideoTrack:(TVIRemoteVideoTrack *)videoTrack
                   publication:(TVIRemoteVideoTrackPublication *)publication
                forParticipant:(TVIRemoteParticipant *)participant {
  
  // We are subscribed to the remote Participant's audio Track. We will start receiving the
  // remote Participant's video frames now.
  
  [self logMessage:[NSString stringWithFormat:@"Subscribed to video track for Participant %@", participant.identity]];
  if (self.participant == participant) {
    [self setupRemoteView];
    [videoTrack addRenderer:self.remoteView];  // 3-8 sec taking to render video. 
  }
}

- (void)setupRemoteView {
  // Creating `TVIVideoView` programmatically
  TVIVideoView *remoteView = [[TVIVideoView alloc] init];
  remoteView.contentMode = UIViewContentModeScaleAspectFill;
  
  self.remoteView = remoteView;
  [self.view insertSubview:self.remoteView atIndex:0];
  
  NSLayoutConstraint *centerX = [NSLayoutConstraint constraintWithItem:self.remoteView
                                                             attribute:NSLayoutAttributeCenterX
                                                             relatedBy:NSLayoutRelationEqual
                                                                toItem:self.view
                                                             attribute:NSLayoutAttributeCenterX
                                                            multiplier:1
                                                              constant:0];
  [self.view addConstraint:centerX];
  NSLayoutConstraint *centerY = [NSLayoutConstraint constraintWithItem:self.remoteView
                                                             attribute:NSLayoutAttributeCenterY
                                                             relatedBy:NSLayoutRelationEqual
                                                                toItem:self.view
                                                             attribute:NSLayoutAttributeCenterY
                                                            multiplier:1
                                                              constant:0];
  [self.view addConstraint:centerY];
  NSLayoutConstraint *width = [NSLayoutConstraint constraintWithItem:self.remoteView
                                                           attribute:NSLayoutAttributeWidth
                                                           relatedBy:NSLayoutRelationEqual
                                                              toItem:self.view
                                                           attribute:NSLayoutAttributeWidth
                                                          multiplier:1
                                                            constant:0];
  [self.view addConstraint:width];
  NSLayoutConstraint *height = [NSLayoutConstraint constraintWithItem:self.remoteView
                                                            attribute:NSLayoutAttributeHeight
                                                            relatedBy:NSLayoutRelationEqual
                                                               toItem:self.view
                                                            attribute:NSLayoutAttributeHeight
                                                           multiplier:1
                                                             constant:0];
  [self.view addConstraint:height];
}

```

#### Expected Behavior

It should render the video immediately after subscribed.

#### Actual Behavior

Its taking more time to render after subscribed video.

#### Reproduces How Often

100%

### Versions

All relevant version information for the issue.

#### Xcode 10.1

[e.g. 9.2]

#### iOS Version 13.3

[e.g. 11.2.6]

**Comment by Balasnest** [comment]
@ceaglest Need your help. Thanks

**Comment by idelgado** [comment]
@Balasnest please provide one or more Room SIDs where you experienced this issue so we can investigate further.

**Comment by Balasnest** [comment]
ROOM ID:  5e85d5edf5c70c8897abcfa8
ROOM SID: 
RM95a5cd9579df6233a5ecb454909e7f04
RM7039d071ed28491ad156fbcb27a07838
RM437b1c80c58b20d8aa880e8318f29e79

@idelgado Will this helpful? Is there any way to log the room sid through objective-c code.

**Comment by Balasnest** [comment]
@idelgado @ceaglest Any updates? I would like to know about the time lag between the subscribed video and add renderer.

**Comment by piyushtank** [comment]
@Balasnest In the log lines provided above, 

```
2020-04-04 23:31:51.902125+0530 app[3123:7123] Subscribed to audio track for Participant 5****
2020-04-04 23:31:51.902775+0530 app[3285:792734] Subscribed to video track for Participant
```

They seem to be running from two different processes and threads. Audiotrack was subscribed on process id 3123 and thread id 7123, while the video track was subscribed on process id 3285 and thread id 792734. 

Can you confirm your setup, use case and how you are trying to use video sdk ?

**Comment by Balasnest** [comment]
@piyushtank Sorry. I have mismatched the log of Subscribed to video track. It ran on the same thread only.  

@ceaglest Are you saying RTT is in higher latency? How can we detect the poor connectivity call? I would like to show it as a warning. This would solve most of the problems.

**Comment by ceaglest** [comment]
Hi @Balasnest,

> How can we detect the poor connectivity call? I would like to show it as a warning. This would solve most of the problems.

You can use the [network quality API](https://www.twilio.com/docs/video/using-network-quality-api) in Group Rooms to detect the quality of the user's connection and show a warning if the quality gets too low.

> @ceaglest Are you saying RTT is in higher latency?

Yes RTT == Round Trip Time. RTT is a measure of the latency for a full round trip to the server and back. This is the reason for @piyushtank's [comment](https://github.com/twilio/video-quickstart-ios/issues/470#issuecomment-610020501) about updating to the latest SDKs and using enabling gll in your console. Your Participants are too far away from us1, the default region.

Best,
Chris

**Comment by Balasnest** [comment]
@ceaglest @piyushtank After changing the media region it improved connectivity and latency a lot better and also I have planned for an upgrade.
 
Closing it for now. will reopen if anything required.

Thanks!
