### ISSUE TITLE
Use of unresolved identifier 'Settings'

### ISSUE THREAD

**Issue by nah2015** [twilio/video-quickstart-ios#471]
I am using code directly from the ViewController.swift.  This section in question results in Swift compiler errors.  "Use of unresolved identifier 'Settings'"

#### Code
           `// Use the preferred audio codec
            if let preferredAudioCodec = Settings.shared.audioCodec {
                builder.preferredAudioCodecs = [preferredAudioCodec]
            }
            
            // Use the preferred video codec
            if let preferredVideoCodec = Settings.shared.videoCodec {
                builder.preferredVideoCodecs = [preferredVideoCodec]
            }
            
            // Use the preferred encoding parameters
            if let encodingParameters = Settings.shared.getEncodingParameters() {
                builder.encodingParameters = encodingParameters
            }

            // Use the preferred signaling region
            if let signalingRegion = Settings.shared.signalingRegion {
                builder.region = signalingRegion
            }`
#### Video iOS SDK

3.2

#### Xcode

11

#### iOS Version

13.4

#### iOS Device

iPhone 11 Pro

**Comment by ceaglest** [comment]
Hi @nah2015,

There is a [Settings](https://github.com/twilio/video-quickstart-ios/blob/master/Utils/Settings.swift) class that the examples depend on. It stores any user configurable state that is selected from the settings UI, and populates default values. It's not necessary to use it if you just want the default ConnectOptions, or have some other way of configuring our SDK.

I hope that helps, but let us know if you have any more questions.

Thanks,
Chris
