### ISSUE TITLE
Unable to cast Screen to a conference

### ISSUE THREAD

**Issue by Raj123456788** [twilio/video-quickstart-ios#474]
### Description: I selected  Broadcast extension  for iOS  .  from Control center and selecting screen Recording.
I am getting an error : BroadcastExtension  has stopped and Access token is expired or expiration date is invalid.

Now if I run from the app itself Once I click Start Broadcast: I don't see any option of BroadcastExtension Project only Record Screen.

[Description of the issue]

### Steps to Reproduce

1. Run the ReplayKit Example on iOS 13.4

#### Code

```swift
// Code that helps reproduce the issue
```

#### Expected Behavior

[What you expect to happen]

#### Actual Behavior

[What actually happens]

#### Reproduces How Often

[What percentage of the time does it reproduce?]

#### Logs
Debug level logs are helpful when investigating issues. To enable debug level logging, add the following code to your application:

```.swift
TwilioVideoSDK.setLogLevel(.debug)
```

```
// Log output when the issue occurs
```

### Versions

All relevant version information for the issue.

#### Video iOS SDK

latest

#### Xcode

Version 11.4 (11E146)

#### iOS Version

13.4

#### iOS Device
ipad

**Comment by Raj123456788** [comment]
@piyushtank: Can you please answer my question?

**Comment by piyushtank** [comment]
@Raj123456788 Can you please fill in the issue template to help us understand the issue? Thanks.

**Comment by Raj123456788** [comment]
Hi @piyushtank , when I run the ReplayKitExample: I am unable to see Broadcast Extenstion. I have followed your Read me. But I am unable test the screen broadcast.
![image](https://user-images.githubusercontent.com/16295521/79241530-053e9300-7e28-11ea-9212-4df17e2d40c3.png)

**Comment by Raj123456788** [comment]
I am seeing this in control Center. And When I click on Broadcast Extension it says Broadcast Extension has stopped due to invalid or expired access Token. 
![ReplayKitControlCenter](https://user-images.githubusercontent.com/16295521/79242862-b1cd4480-7e29-11ea-9195-51bc195fc9e8.png)

**Comment by piyushtank** [comment]
@Raj123456788  Can you check if the token you are using is valid?

**Comment by Raj123456788** [comment]
Yes, I created token this morning.

**Comment by Raj123456788** [comment]
@piyushtank :Can you please help me with my question?

**Comment by ceaglest** [comment]
Hey @Raj123456788,

Access tokens created using the [Testing Tools page](https://www.twilio.com/console/video/project/testing-tools) are only valid for 60 minutes after creation.

We also have a [tutorial for access tokens](https://www.twilio.com/docs/video/tutorials/user-identity-access-tokens) with more info on creating them yourself.

Cheers,
Chris

**Comment by Raj123456788** [comment]
Hi @ceaglest , I tested within 60 mins and got the above error. But why I don't see the Broadcast extension option? Please see the images attached.

**Comment by ceaglest** [comment]
Hi @Raj123456788,

> I tested within 60 mins and got the above error

Is it the access token expired error, or not being able to see video from the broadcast?

> when I run the ReplayKitExample: I am unable to see Broadcast Extenstion.

ReplayKitExample doesn't render remote video tracks. You can use most of our other sample apps like the [Quickstart](https://github.com/twilio/video-quickstart-ios/tree/master/VideoQuickStart) to render remote video.

Cheers,
Chris

**Comment by ceaglest** [comment]
Closing since I didn't hear back from you. Let me know if you need more help with screencast.
