### ISSUE TITLE
[Question] No audio signal, when using Call Kit 

### ISSUE THREAD

**Issue by sebohdev** [twilio/video-quickstart-ios#479]
Hi everyone,

I'm currently trying to get the ViewController+CallKit.swift running. My use case is, that via PushKit I get a notification, for an incoming call, and then via CXProvider I register an incoming call. If the screen is not locked I have no issue so far, but if the screen is locked I only can hear the other user/participant, but the other one can't hear me.

I checked if the audio track is published and so on and it seems correct. Can't see any issues here. Also the permission granted to use audio.

My question is, whether I need to configure anything else to make sure my microphone is working.

Thanks & Best
Sebastian

**Comment by piyushtank** [comment]
@sebohdev Apologies for the delay. Thanks for reaching out.
Can you confirm that you are using the guidelines provided by our [CallKit example](https://github.com/twilio/video-quickstart-ios/tree/master/VideoCallKitQuickStart) ? Also, can you provide RoomSID, and logs? You can share logs with us via a support ticket or you can share via email to me ptank@twilio.com

Please enable following logs -
```swift
        
        TwilioVideoSDK.setLogLevel(.debug, module: .platform)
        TwilioVideoSDK.setLogLevel(.debug, module: .core)
        TwilioVideoSDK.setLogLevel(.debug, module: .webRTC)
```

**Comment by piyushtank** [comment]
Closing this ticket but feel free to re-open or post another ticket if you have any issue.
