### ISSUE TITLE
dyld-abort-with-payload-with-no-error-message

### ISSUE THREAD

**Issue by srsstyle1** [twilio/video-quickstart-ios#480]
> Before filing an issue please check that the issue is not already addressed by the following:
>
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelog-twilio-video-ios-version-2x).
> 
> If this is an issue with the QuickStart itself, file it here. If this is an issue with the SDK or how to do something with the SDK please use [twilio-video-ios](https://github.com/twilio/twilio-video-ios/issues) instead.
>
> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description

[Description of the issue]

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. [Insert as many steps as needed]

#### Code

```swift
// Code that helps reproduce the issue
```

#### Expected Behavior

[What you expect to happen]

#### Actual Behavior

[What actually happens]

#### Reproduces How Often

[What percentage of the time does it reproduce?]

#### Logs
Debug level logs are helpful when investigating issues. To enable debug level logging, add the following code to your application:

```.swift
TwilioVideoSDK.setLogLevel(.debug)
```

```
// Log output when the issue occurs
```

### Versions

All relevant version information for the issue.

#### Video iOS SDK

[e.g. 1.3.12 via CocoaPods]

#### Xcode

[e.g. 9.2]

#### iOS Version

[e.g. 11.2.6]

#### iOS Device

[e.g. iPhone 8 Plus]

**Comment by srsstyle1** [comment]
App crashes in real device with this error message 
Xcode-11.0

**Comment by ceaglest** [comment]
Hi @srsstyle1,

Is there any error message or debugger output that you can share? 

If you're using manual integration or Carthage it sounds like you haven't embedded the TwilioVideo.framework binary in your application. See the guide for [manual integration](https://www.twilio.com/docs/video/ios-getting-started#manual) and [carthage integration](https://www.twilio.com/docs/video/ios-getting-started#carthage) for more information.

Thanks,
Chris

**Comment by ceaglest** [comment]
Hi @srsstyle1,

If you are using Xcode 13.3.1 and a free Apple developer account there is an issue with code signing that may cause this crash. If this is the case, take a look at https://github.com/twilio/video-quickstart-ios/issues/460#issuecomment-599621547 for more information.

Best,
Chris

**Comment by ceaglest** [comment]
Hi @srsstyle1,

Closing this issue since I didn't hear back from you. Hopefully you were able to resolve the dynamic loader issue. If not reopen the issue and we can diagnose further.

Best,
Chris
