### ISSUE TITLE
make video view to float over app [HELP]

### ISSUE THREAD

**Issue by parvbhaskar** [twilio/video-quickstart-ios#483]
I was trying to add the MultiPartyViewController as a child view on the appdelegate's window object to make it visible all over the app to make it similar like the whats'app video call feature.

But at that time the only message getting printed is "Attempting to connect to room:" after that nothing happen.

Is there any other way I can achieve this, so that user should feels same like the whatsapp.

**Comment by parvbhaskar** [comment]
for the code reference I'm using exectly the same viewcontroller "MultiPartyViewController" by passing roomID and accesstoken

**Comment by ceaglest** [comment]
Hey @parvbhaskar,

This is a good question. I'm sure a floating video view could be achieved with custom parent / child view controllers but there may be a simpler way to do it.

I should mention that the MultiPartyExample has been removed in favor of [twilio-video-app-ios](https://github.com/twilio/twilio-video-app-ios) which is a more fully featured multi-party collaboration app. Unfortunately, the floating video view UI isn't implemented there either.

Let me see if there is anyone who could help you further with this question.

Best,
Chris

**Comment by timrozum** [comment]
Hi @parvbhaskar,

I think you're probably on the right track using UIWindow to add a global view. Can you confirm that you have gotten video to work correctly inside a simple view controller? And also that you have a simple global view working without video? Want to make sure those are working independently before combining concepts.

Tim

**Comment by parvbhaskar** [comment]
@ceaglest thanks for the update about MultiPartyExample, is the new video view has support video 8-10 urs connected to video call ??, thanks for the help by providing the parent child concept, but currently I have been using the uiwindow option to continue my functionality.

@timmydoza yes I have successfully manage to add the video view on UIWindow and change its size to support other app features to worked parallel and also able to use move it around the screen using panGesture. Still working on adding some more features and UI changes.

**Comment by timrozum** [comment]
@parvbhaskar is your video update issue fixed or is it still a problem?

**Comment by timrozum** [comment]
@parvbhaskar yes the video product can support up to 50 participants.

I'm going to close this issue but if you have any other questions just let me know and we can reopen.

**Comment by parvbhaskar** [comment]
@timrozum thanks yes it is fixed
