### ISSUE TITLE
53005 "DNS resolution for signaling failed"

### ISSUE THREAD

**Issue by dsngeu** [twilio/video-quickstart-ios#485]
I am getting this error from delegate when I try to connect room via valid token and valid room name for video call 

func roomDidFailToConnect(room: Room, error: Error) {
Error Domain=com.twilio.video Code=53005 "DNS resolution for signaling failed" UserInfo={NSLocalizedDescription=DNS resolution for signaling failed}
}

how to solve this problem? 
what is reasons of this error?

**Comment by ceaglest** [comment]
Lets use the other issue you filed: https://github.com/twilio/twilio-video-ios/issues/91
