### ISSUE TITLE
Empty credentials in Twilio debugger from iOS

### ISSUE THREAD

**Issue by yatindma** [twilio/video-quickstart-ios#487]
I am trying to initiate a call from iOS then it's connecting for 2-3 sec and getting disconnected after that and in Twilio debugger we are getting "Empty Credentials", do you have nay idea regarding the same.

**Comment by ceaglest** [comment]
Hey @yatindma,

If I understand your question then I think the best place to discuss is in: https://github.com/twilio/voice-quickstart-ios/issues/342
