### ISSUE TITLE
To receive  incoming call on locked iphone

### ISSUE THREAD

**Issue by ishangrover23** [twilio/video-quickstart-ios#488]
twilio / video-quick-start is working well in all cases, but the one issue is that when phone is locked and we throw the Voip for picking the video call my app is not coming in foreground mode. but when i manually open the app my video is working well. I want to open app automatically when i pick the video
call via voip
can you please help me for that issue 

Thanks in Advance.
issue in iPad/iPhone
iOS :- 13

**Comment by piyushtank** [comment]
@ishangrover23 What you are observing is iOS CallKit + PushKit behavior and unfortunately it's not in VideoSDK's control. CallKit is primarily designed for audio calls - that allows users to talk when the app is not in foreground. Until Apple releases a framework/feature for video calls, we will have to work around with the CallKit limitations.

**Comment by ishangrover23** [comment]
@piyushtank Thanks for your reply , I was also thinking about this (we will have to work around with the CallKit limitations.) so i just want to confirm if i was doing something wrong.

Now for if phone is locked i am using push notification same like as another apps rather then CallKit
