### ISSUE TITLE
Audio gets disconnected when phone call received

### ISSUE THREAD

**Issue by Balasnest** [twilio/video-quickstart-ios#491]
# Description
1. Audio gets disconnected whenever a phone call received. 
2. Most of the user complains Bluetooth earphones does not work with a video call and audio is not audible with/without a headset.

### Steps to Reproduce

1. Both parties are connected
2. Do phone calls and pick while connected.
3. Audio doesn't work after come back to the room.

#### Expected Behavior

Audio should work after return from the PSTN call. 
Note: It should work with bluetooth (users are complaining. but couldn't reproduce yet)

#### Actual Behavior 

Audio doesn't work after return from calls.

#### Reproduces How Often

It's happening with phone calls

### Versions

All relevant version information for the issue.

#### Video iOS SDK

[3.2.5]

#### Xcode

[11]

#### iOS Version

[13.4.1, 13.1]

#### iOS Device

[iPhone XR, iPhone SE]

**Comment by Balasnest** [comment]
@paynerc @ceaglest I need your help. Thanks!

**Comment by paynerc** [comment]
@Balasnest,

A couple of questions to get started:

1. Is your application using CallKit?
2. Do you have debug logs that you could share when this situation occurs?
3. Do you have any RoomSids that you could share when this situation occurs?
4. Any code surrounding the use of `TVIAudioDevice` and `TVIDefaultAudioDevice`.

Bluetooth connections to things like cars and headphones should "just wok" out of the box. Take a look at the Twilio Video Collaboration application: https://github.com/twilio/twilio-video-app-ios. We use this internally for many of our meetings and I often use bluetooth headsets or the bluetooth in my vehicle and it "just works".

If you don't feel comfortable sharing this information in this pubic GitHub issue you can send an email to support@twilio.com, include the information requested, reference this issue and mention that I asked you to send that information along. If you do chose to go this route, please respond here with the support issue number so I can find it.

In the meantime, I will try and reproduce this issue with our Quickstart applications to see if I get the same behavior.

Thank you,

Ryan

**Comment by paynerc** [comment]
@Balasnest,

Are you still experiencing issues with this?

Ryan

**Comment by Balasnest** [comment]
@paynerc  Yes. I am not using callKit. Once disconnected phone calls (network) and come back, audio is not connecting. Will reproduce tomorrow and share SID.

**Comment by paynerc** [comment]
@Balasnest,

Are you still experiencing this issue? If so can you please send the Room SID and any debug logs that you have when this issue occurs?

Thank you, 

Ryan
