### ISSUE TITLE
dyld: Library not loaded: @rpath/TwilioVideo.framework/TwilioVideo

### ISSUE THREAD

**Issue by BayCem** [twilio/video-quickstart-ios#494]
Hi,

I am trying to use TwilioVideo in the project. I added TwilioVideo with a pod and when I am trying to install to real device(just real device), app crashes with the given error:

`dyld: Library not loaded: @rpath/TwilioVideo.framework/TwilioVideo`

What I tried so far:

- Tried with Paid Developer Account.
- Tried to change build system to Legacy.
- Tried to delete `#use_frameworks!` and/or `#use_modular_headers!` from pod file.
- Tried to test different real devices(with different iOS versions).

Every time error does not fixed.

Then I created different project with using different dependencies. In that dependencies I got the same error but I tried above methods and the methods fixed the issue.

When I delete TwilioVideo, problem gone but I need to use TwilioVideo.

**Comment by piyushtank** [comment]
@BayCem This sounds like either library is not copied properly or not available at the location it expects. Can you try again with following the [instructions](https://www.twilio.com/docs/video/ios-getting-started#1-get-the-programmable-video-ios-sdk) on how to add TwilioVideo library in your ios xcode proejct? Thanks.

**Comment by BayCem** [comment]
Thanks for reply @piyushtank. I was installing `TwilioVideo` with using `Cocoapods`. 
Right now, I tried installing `TwilioVideo` manually.

* I downloaded `TwilioVideo.framework.zip`
* I added `TwilioVideo.framework` in `Project->General->Frameworks, Libraries, and Embeded Content` Section and I selected `Embed & Sign`(am I adding correct location?).
* After that I saw `TwilioVideo.framework` in `Project->Build Phases->Link Binary With Libraries`.
* Then in `Project->Build Phases->Link Binary With Libraries`, I added all of these:
```
AudioToolbox.framework
VideoToolbox.framework
AVFoundation.framework
CoreTelephony.framework
GLKit.framework
CoreMedia.framework
SystemConfiguration.framework
libc++.tbd
```
* Then, I updated `Project->Build Settings->Other Linker Flags` with adding `-ObjC`
* After that, I go to `Project->Build Phases` and I added` Run Script `after the `Embed Frameworks`. You can `Run Script` details in [image](https://imgur.com/a/1McBvlk).


Finally, I plug the iPhone, and still I am getting error. The error states that:

```
ld: framework not found TwilioVideo
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by BayCem** [comment]
Still waiting, still not solved. @piyushtank

**Comment by piyushtank** [comment]
@BayCem Can you make sure the Xcode project has the TwilioVideo framework in embedded framework section.
<img width="940" alt="Screen Shot 2020-05-28 at 10 27 59 AM" src="https://user-images.githubusercontent.com/17037593/83173487-f1947680-a0cd-11ea-891f-681c5fa74b6d.png">

Make sure, you do "copy and save" when you pull TwilioVideo.framework in to your project.

If you still have no luck, try with some other framework other than TwilioVideo.framework and see if that works.

**Comment by BayCem** [comment]
@piyushtank, thank you for reply. I added into embeded section but somehow it does not work.
After that I deleted twiliovideo.framework and installed as a pod again at this time somehow it's start working.

**Comment by cvdevmaster** [comment]
@piyushtank

I am getting the same issue... 

 I am adding TwilioVideo Swift Package into a framework. Then adding the framework into my main target via linking.. it works for every other framework such as Stripe, Firebase.. but not Twilio. 

How can I achieve this with Twilio?
