### ISSUE TITLE
Live Camera/streaming using twilio video SDK

### ISSUE THREAD

**Issue by aksthelion** [twilio/video-quickstart-ios#497]
Is it possible to use Twilio Video SDK to stream as live camera? I'm trying to implement a live camera in iOS. This will not be a video call but a live streaming with no user interaction. Is it possible? If yes then please provide some hints. I've been searching but didn't find any mention.

**Comment by piyushtank** [comment]
@aksthelion it should be possible but before I confirm, can you provide the details of the use case that you are trying to achieve?

**Comment by aksthelion** [comment]
In my mobile & web apps I want to show a user's live stream. Streamer will live stream from the app itself. It will be like a typical live camera kind of thing. It's simple usage. Let me know if I've made requirement clear?

**Comment by piyushtank** [comment]
@aksthelion Apologies for the late response. The streaming itself is not yet supported where you can have thousands of users can view your contents. The feature is in the pipeline but I dont have time line yet as it is still under the discussion. However in our group Rooms, you can still have one way media to all participants in the Room.

**Comment by piyushtank** [comment]
Closing the ticket as answered. Feel free to reopen or open a new ticket if you run into issue or have any questions.

**Comment by apexkid** [comment]
Does rooms support over 50 users?

**Comment by olivier545** [comment]
@piyushtank
Can you please explain how to have one way media to all participants in the Room (=> only main participant video, other participants can't activate video nor speakers).
Thanks

**Comment by aksthelion** [comment]
Just wanted to update that after exploring a lot of options it seems the only way forward is WebRTC. We have manage to implement streaming and enhancing it for full both way video chat. If we manage to implement it then we may not need Twilio at all. 

It's sad that there is no other alternative for an out of box full streaming solution. To all those who want to implement streaming/broadcasting you should look for WebRTC route. Twilio is not the right candidate.

**Comment by ceaglest** [comment]
Hi @aksthelion,

We don't support broadcasting at the moment but this is something that we are still interested in. (WebRTC on its own is not a broadcast / streaming solution either). 

I'm sorry that we are not able to meet your requirements today, but good luck with your broadcasting endeavour.

Best,
Chris
