### ISSUE TITLE
Set frame on local Stream for receiver display

### ISSUE THREAD

**Issue by UjeshPatelSA** [twilio/video-quickstart-ios#498]
Facing Frame issues 

I Want to set frame on iOS local stream for display video on web app with fix frame. 
in web to web video call. we set frame like as below for each local track 

Here is web Code for reference 
```
localTrackOptions: {
                    audio: true,
                    video: {
                        height: '190',
                        width: '280',
                    },
                }, 
....
....
Twilio.Video.createLocalTracks(options.localTrackOptions)

```

With Current iOS code. it's display full screen video on web App. but need to fix display frame up to (280,190) on web app from iOS app.

**Comment by piyushtank** [comment]
@UjeshPatelSA Can you confirm - are you using java script SDK or iOS TwilioVideo SDK in your app? I recommend posting your question on https://github.com/twilio/twilio-video.js/issues for JavaScript Video SDK specific questions.

**Comment by ujeshpatel** [comment]
Thanks for the response,  Using iOS TwilioVideo SDK

**Comment by UjeshPatelSA** [comment]
Thanks for reply, using iOS TwilioVideo SDK

**Comment by piyushtank** [comment]
@UjeshPatelSA You can use use our Video source apis to get the output format of your choice. See the [guide](https://www.twilio.com/docs/video/video-source-apis).

**Comment by piyushtank** [comment]
Closing the ticket as answered. Feel free to reopen or open a new ticket if you run into issue or have any questions.
