### ISSUE TITLE
How to identify specific track?

### ISSUE THREAD

**Issue by namanAstapartners** [twilio/video-quickstart-ios#502]
As a receiver i want to identify whether incoming video track is normal video track[video Call] or it is screen Capture track[screen record].. 

[<TVIRemoteVideoTrackPublication: 0x10ed2eed0>
    trackSid: ***
    trackName: ***
    isEnabled: NO
]

by looking into publication details I only find this three values which is something we need to taken care from sender side right? or is there any way to differentiate from mobile side..

in our case sender is **AdminPanel** and receiver is **iOS**.

**Comment by ceaglest** [comment]
Hey @namanAstapartners,

I would recommend using some sort of special name like "Screen" to identify the screen captured track. For example:

```
        screenTrack = LocalVideoTrack(source: videoSource,
                                      enabled: true,
                                      name: "Screen")
```

Best,
Chris
