### ISSUE TITLE
Video freezing after seconds from joining the room.

### ISSUE THREAD

**Issue by MhmdRizk** [twilio/video-quickstart-ios#506]
### Description

First I ran the quickstart app on two different iPhones and tested it and it's working perfectly.
Anyway I copied the whole flow into the new app I want to create, everything is working perfectly for the first few seconds then The video is freezing.
what I mean by freezing that I can see my own preview and the recipient can see his own preview, but the participant and the recipient can see only the last captured image of the video.

I tried this from iOS to iOS and faced this issue.

I tried this from Android to Android and didn't face this issue.

I tried this from iOS to Android and vice versa, only the android see a frozen video.

so I think the issue is while sending the video.

a final note that the voice track is working perfectly, only the video track is freezing.

#### Logs
logs from app A on iOS
RIZK:-LoggingCalls ::: Video track created
RIZK:-LoggingCalls ::: Attempting to connect to room XXXXXXXXX
RIZK:-LoggingCalls ::: Video track created
RIZK:-LoggingCalls ::: Connected to room XXXXXXXXX as YYYYYYYYYY
RIZK:-LoggingCalls ::: Participant ZZZZZZZZZ connected with 1 audio and 1 video tracks
RIZK:-LoggingCalls ::: Subscribed to WWWWWWWWWWWW audio track for Participant ZZZZZZZZZ
RIZK:-LoggingCalls ::: Subscribed to RRRRRRRRRRRRRRRR video track for Participant ZZZZZZZZZ

logs from app B on iOS
RIZK:-LoggingCalls ::: Video track created
RIZK:-LoggingCalls ::: Attempting to connect to room XXXXXXXXX
RIZK:-LoggingCalls ::: Video track created
RIZK:-LoggingCalls ::: Connected to room XXXXXXXXX as NNNNNNNNN
RIZK:-LoggingCalls ::: Subscribed to Microphone audio track for Participant DDDDDDDDD
RIZK:-LoggingCalls ::: Subscribed to Camera video track for Participant DDDDDDDDD

### Versions

Video app version: - TwilioVideo (~> 3.0)
iOS version: 13.5, 13.5.1, 13.4
Device: iPhone XS, iPhone X, iPhone 6s
Xcode version: 11.3.1

**Comment by paynerc** [comment]
@MhmdRizk,

First off I would like extend an apology for not responding to this issue sooner.

Are you still experiencing this issue? Above you stated that you are using TwilioVideo (~>3.0). Can you tell me the exact version that you are consuming?

One thing that would be helpful is if you could provide room sids where this occurs as well as debug level logs from the iOS device?

You can email them to support@twilio.com, reference this Github issue and then post the issue number here and I can get to the information. Those pieces of info will help get us started troubleshooting what is going on.

I look forward to hearing back from you on this.

Ryan

**Comment by Balasnest** [comment]
This issue is causing in **android** and *iOS*. Huge delay in rendering remote video First frame. Will collate and share SID tomorrow. I have already raised on other thread. Please look into this on priority.

**Similar issue related to iOS:**
[ios - 214](https://github.com/twilio/video-quickstart-ios/issues/214) 
[ios - 240](https://github.com/twilio/video-quickstart-ios/issues/240)
[ios - 275](https://github.com/twilio/video-quickstart-ios/issues/275)

**Similar issue related to RN:**
[RN - 94](https://github.com/blackuy/react-native-twilio-video-webrtc/issues/94)

**Comment by paynerc** [comment]
@MhmdRizk,

Just checking in to see if you had a chance to provide Room Sids to help troubleshoot this issue.

Thank you,

Ryan

**Comment by paynerc** [comment]
@MhmdRizk,

Are you still experiencing this issue?

Ryan

**Comment by paynerc** [comment]
Closing this issue as we have no received a response for this in a while. Please feel free to reopen and provide the further requested info.

Ryan
