### ISSUE TITLE
Not able to stop Twilio audio

### ISSUE THREAD

**Issue by gurupatel** [twilio/video-quickstart-ios#510]
I want to stop/unstop Twilio audio same as zoom app does. We are asking our user to enable/disable internet audio permission same as zoom, so for that we need to **stop** whole audio session if it is not enable & **unstop** if it is enable by our users. 

So if audio session (Internet audio) is not enable by user, then user should not able to hear any audio from any participant connected in room & also audio should not go from device to other participant.  

Please find the attached screen shot for more clarity. 

![WhatsApp Image 2020-06-23 at 12 12 20 PM](https://user-images.githubusercontent.com/3120193/85369573-f290ba80-b54a-11ea-8078-3c0ff40bd136.jpeg)

**Comment by piyushtank** [comment]
@gurupatel I am assuming you are not using CallKit in your app. 
Have you tried using [DefaultAudioDevice.enabled](https://twilio.github.io/twilio-video-ios/docs/latest/Classes/TVIDefaultAudioDevice.html#//api/name/enabled) property? It stops and starts audio unit on demand.  Try using it and let me know how it goes.

**Comment by gurupatel** [comment]
@piyushtank Working perfect, thanks for fast & proper reply.
