### ISSUE TITLE
Higher quality+resolution frames in local renderer

### ISSUE THREAD

**Issue by andschdk** [twilio/video-quickstart-ios#512]
Hi,
Currently I'm processing some frames from a custom renderer attached to a local video track.

However the frames are in low resolution (480x640). If I need a higher quality/resolution how would you suggest I approach it? I'm only talking about the local video track, assuming higher quality should be possible here.

I'm not sure how things are related to `AVCaptureSession`, but I guess it has something to do with the [`sessionPreset`](https://developer.apple.com/documentation/avfoundation/avcapturesession/1389696-sessionpreset)? 

Thanks.

**Comment by piyushtank** [comment]
@andschdk Apology for the late response.

The Video SDK doesnot use sessionPreset to configure the resolution, instead, we use the VideoFormat APIs for developers to configure the dimenstions of their choice, and internally, in capture pipeline, we apply the activeFormat on the `AVCaptureDevice`. 

With Video SDK you can definitely high resolution video by applying the appropriate VideoFormat. See [video source guide](https://www.twilio.com/docs/video/video-source-apis) for more information. Also our Video app demonstrates some of the 
 video source [configuration](https://github.com/twilio/twilio-video-app-ios/blob/8af8be6609af350ef7bc59a51d80fdd708e3cce0/VideoApp/VideoApp/Video/Tracks/Camera/CameraManager.swift) features.

Let me know if you have any questions.

**Comment by piyushtank** [comment]
Closing the ticket as answered. Feel free to reopen or open a new ticket if you run into issue or have any questions.

**Comment by andschdk** [comment]
Thank you for this! 👍
