### ISSUE TITLE
How to disable video recording except prod?

### ISSUE THREAD

**Issue by Balasnest** [twilio/video-quickstart-ios#514]
Just a query:

I want to disable the video recording feature on Dev and QA environment. How can we achieve this? Is it there any API to disable while making video call request?

**Comment by paynerc** [comment]
@Balasnest 

First I'd like to apologize for the late response getting back to you.

I'm assuming you are talking about your environments, Production, QA and Dev, correct? At the current time, recording is set on a group room when the room is created. So it all depends on how you are creating your rooms. 

If you are using the [REST API](https://www.twilio.com/docs/video/api/rooms-resource) to [create rooms](https://www.twilio.com/docs/video/api/rooms-resource#create-room), you can provide the `RecordParticipantsOnConnect` parameter to enable recordings or disable recordings.

If you are creating ad-hoc rooms, that is the room is created when the first participant connects, the default parameter for recording is used. This parameter is set from the [Rooms Settings page](https://www.twilio.com/console/video/configure) in the console. If you wanted to have different values for recordings, you could create Twilio sub accounts for each of your environments with the recoding setting as appropriate for that environment. You would then use the sub account info when creating tokens for the different environments. This would ensure that the appropriate sub account and settings are used when connecting to the room.

Being able to stop and start recordings after the room is created is on the product roadmap, but I do not have a timeframe of when that will be available.

Please let me know if you have any further questions regarding this approach.

Ryan

**Comment by Balasnest** [comment]
@paynerc Thanks you for addressing this. I am cleared now. It's great to hear new things.
