### ISSUE TITLE
Fatal runtime capture error

### ISSUE THREAD

**Issue by dmichelutti** [twilio/video-quickstart-ios#517]
Hi, I have an error when using Twilio in call with multiple users. This error is shown when main video source is changed from first user to another one. The result is a black screen.

ERROR:Twilio:[Platform](0x171277000): Fatal runtime capture error: Error Domain=AVFoundationErrorDomain Code=-11800 "L'operazione non è stata completata" UserInfo={NSLocalizedFailureReason=Si è verificato un errore sconosciuto (-12780), NSLocalizedDescription=L'operazione non è stata completata, NSUnderlyingError=0x283691230 {Error Domain=NSOSStatusErrorDomain Code=-12780 "(null)"}}, code -11800
Capture failed with error.
code = -11800 error = L'operazione non è stata completata

Do this error be caught?

**Comment by paynerc** [comment]
@dmichelutti,

What version of Twilio Video iOS are you using?

I am not sure I understand what you mean by this:

> This error is shown when main video source is changed from first user to another one.

Are you talking about changing the source where your local video is coming from with the camera, or the UI in your app where you are changing the video being displayed in your main UI window?

The error you are describing is coming from our camera capture pipeline. Off the top of my head I am thinking that you are creating multiple `TVICameraSource` objects and they are competing for the single camera resource.

Would you be able to share debug logs for the application where you are seeing this as well as what you mean in the statement above.

Thank you,

Ryan

**Comment by paynerc** [comment]
@dmichelutti,

It's been a couple weeks since I've heard from you? Are you still facing this issue? I am going to close this issue but feel free to reopen it if you have more information tp provide.

Ryan
