### ISSUE TITLE
Why latest version pod not installing?

### ISSUE THREAD

**Issue by mouli457** [twilio/video-quickstart-ios#527]
![Screenshot 2020-07-21 at 6 09 55 PM](https://user-images.githubusercontent.com/39989237/88056027-84590b00-cb7d-11ea-85b3-8b6a93ec4c63.png)
I am using pod 'TwilioVideo' for installing TwilioVideo,but it installing version(2.10.2).I am using Xcode 11.2.1.Please tell me solution.Thanks in advance.

**Comment by ceaglest** [comment]
Hey @mouli457,

Twilio Video 3.5 is  being referenced in your Podfile. We recommend that you use the latest version but you must raise your deployment target to iOS 11.0 to do so. Checkout the [Podfile](https://github.com/twilio/video-quickstart-ios/blob/master/Podfile) in this repo for an example supporting version 3.5.

```
// ... snip

  pod 'TwilioVideo', '~> 3.5'

  target 'ARKitExample' do
    platform :ios, '11.0'
    project 'ARKitExample.xcproject'
  end

// ...
```

Let me know if you were able to get it working.

Thanks,
Chris

**Comment by ceaglest** [comment]
I'm assuming you got past this based upon the other issue that you filed. If you're still having trouble please re-open and I can assist further.
