### ISSUE TITLE
VoIP Notification

### ISSUE THREAD

**Issue by smartphone-pro** [twilio/video-quickstart-ios#528]
### Description

I'm building a one-on-one video call.
When I start the call, I want to send the VoIP push notification to the recipient.
I think Twilio does not notify the recipient by default because the video call is based on the room.
Is there a RestAPI that sends VoIP push notification to the recipient, such as a one-on-one voice call?
Thank you.

### Versions

All relevant version information for the issue.

#### Voice iOS SDK

TwilioVideo 3.5.0 via CocoaPods

#### Xcode

11.5

#### iOS Version

13.5.1

#### iOS Device

iPhone 7 Plus
iPhone Pro Max

**Comment by piyushtank** [comment]
@smartphone-pro Before I could answer, can you let us know if you plan to add video in your app using TwilioVideo SDK or will it be just a voice (audio only) calls?

**Comment by smartphone-pro** [comment]
@piyushtank Thank you for your reply.
I am building an integrated voice and video call app.

one-to-one voice call
voice conference
one-to-one video call
video conference

I'd like to implement all of the above.
I've already implemented all the functions, but I only need to carry out VoIP notifications during the one-on-one video call.

I look forward to your kind cooperation.
Thank you.

**Comment by smartphone-pro** [comment]
@piyushtank Hello.
Would you please answer the question?

**Comment by piyushtank** [comment]
@smartphone-pro You will have to build your own signaling using[ Twilio Notify ](https://www.google.com/search?q=twilio+notify&rlz=1C5CHFA_enUS898US898&oq=twilio+notify&aqs=chrome..69i57j0j69i60l6.3015j0j4&sourceid=chrome&ie=UTF-8)to receive incoming call push notification. one-to-one and conference on video and voice is supported by Video SDK.
