### ISSUE TITLE
How to know remote participant access mobile participant video?

### ISSUE THREAD

**Issue by Chandu457** [twilio/video-quickstart-ios#534]
How could I know when remote participant access my screen?Thanks in advance.

**Comment by piyushtank** [comment]
@Chandu457 By default, all participant are auto subscribed to the published tracks. The Video SDK doesn't have an API to get the list of all participant subscribed to a specific track, with our current APIs you can make an assumption that all participants are subscribed to the published tracks. Let me know if you have any questions.
