### ISSUE TITLE
Audio/ Mic is not working when go to background & come back again

### ISSUE THREAD

**Issue by musheer-ahamed** [twilio/video-quickstart-ios#536]
Hi,
I have implemented chatting app with calling feature. I am facing audio/mic issue in live app.
I have audio/mic issue when go to background and come back to app during call. Some time audio is not working. Some time mic is not working. please anyone help me to solve this issue.

**Comment by ceaglest** [comment]
Hey @musheer-ahamed,

At first glance, does your app have permissions to use audio in the background?

See [Getting Started - Backround Modes](https://www.twilio.com/docs/video/ios-getting-started#background-modes) for the entitlements that you need.

Best,
Chris

**Comment by musheer-ahamed** [comment]
@ceaglest Thanks!
I have enabled voice over IP, picture In picture, background fetch, remote notification. 
While app was in background audio & mic both are working fine. but when entering to foreground from background this issue was happens.

**Comment by musheer-ahamed** [comment]
@ceaglest 
When comes foreground from background, I have tried to unpublish localAudio track and after 1 sec I have again created new audio track and published. Then also the same issue happening. Please help me. This is live production issue. I have to fix soon.

**Comment by ceaglest** [comment]
Hi @musheer-ahamed,

If you could provide client side logs and a Room SID I would be happy to look into this further. For now I suggest comparing to the Quickstart example app to see what the differences are. I am able to background the example app and come back with audio functional.

> When comes foreground from background, I have tried to unpublish localAudio track and after 1 sec I have again created new audio track and published.

I don't recommend publishing and unpublishing in the background. If no one is publishing audio in a Room then your AVAudioSession will get interrupted.

Best,
Chris

**Comment by musheer-ahamed** [comment]
@ceaglest Thanks!
I have tried with removed all my foreground/background functions. Still, the mic is not working when come to foreground from background.
Sorry @ceaglest I can't get logs from testflight. I'm working on a remote system so I'm unable to connect the device to the system and get logs. I have attached room sid. Please give me some suggestions. I'm in trouble now. This is production issue. 

Room SId:
RM697de0e1fde5d17652e18ca475d21be9

Devices details:
iPhone 7+, OS 13.3.1
iPhone 6s+, OS 13.6

This is my coding details:

func performRoomConnect(uuid: UUID, roomName: String? ) {
        enableAudioBlock(isEnable: false)
        
        prepareLocalMedia()
        // Preparing the connect options with the access token that we fetched (or hardcoded).
        let connectOptions = ConnectOptions(token: accessToken) { (builder) in
            
            // Use the local media that we prepared earlier.
            builder.audioTracks = self.localAudioTrack != nil ? [self.localAudioTrack!] : [LocalAudioTrack]()
            
            builder.videoTracks = [LocalVideoTrack]()
            
            // Use the preferred audio codec
            if let preferredAudioCodec = Settings.shared.audioCodec {
                builder.preferredAudioCodecs = [preferredAudioCodec]
            }
            
            // Use the preferred video codec
            if let preferredVideoCodec = Settings.shared.videoCodec {
                builder.preferredVideoCodecs = [preferredVideoCodec]
            }
            
            // Use the preferred encoding parameters
            if let encodingParameters = Settings.shared.getEncodingParameters() {
                builder.encodingParameters = encodingParameters
            }
            
            // Use the preferred signaling region
            if let signalingRegion = Settings.shared.signalingRegion {
                builder.region = signalingRegion
            }
            
            builder.isNetworkQualityEnabled = true
            builder.networkQualityConfiguration = NetworkQualityConfiguration(localVerbosity: .minimal,
                                                                              remoteVerbosity: .minimal)
            
            builder.roomName = roomName
            builder.isDominantSpeakerEnabled = true
        }
        
        // Connect to the Room using the options we provided.
        room = TwilioVideoSDK.connect(options: connectOptions, delegate: self)
    }



func enableAudioBlock(isEnable: Bool = true) {
        self.audioDevice.isEnabled = isEnable
        self.audioDevice.block()
    }

    func prepareLocalMedia() {
        // Create an audio track.
        if (localAudioTrack == nil) {
            if DataSource.getInstance().isFromVOIP {
                localAudioTrack = LocalAudioTrack()
            }else {
                localAudioTrack = LocalAudioTrack(options: nil, enabled: true, name: "Microphone")
            }
            if (localAudioTrack == nil) {
                print( "Failed to create audio track")
            }
        }
        if !isAudioCall {
            checkLocalVideoRendering()
            startPreview()
        }
    }

func roomDidConnect(room: Room) {
for remoteParticipant in room.remoteParticipants {
            remoteParticipant.delegate = self
        }
enableAudioBlock()
switchAudioDevice(toSpeaker: false)
}

func switchAudioDevice(toSpeaker: Bool) {
        
        
        audioDevice.block = {
            DefaultAudioDevice.DefaultAVAudioSessionConfigurationBlock()
            do {
                let audioSession = AVAudioSession.sharedInstance()
                try audioSession.setMode(toSpeaker ? AVAudioSessionModeVideoChat : AVAudioSessionModeVoiceChat)
                self.isSpeakerEnabled = toSpeaker
                try audioSession.overrideOutputAudioPort(AVAudioSession.PortOverride.none)
            } catch let error as NSError {
                print("Fail: \(error.localizedDescription)")
            }
        }
        audioDevice.block()
        self.localAudioTrack?.isEnabled = self.localAudioTrack?.isEnabled ?? false
    }

**Comment by musheer-ahamed** [comment]
@ceaglest 
I am playing a ring tone before answering the call. also I'm playing the ringing sound to the caller side up to receiver joins the call. This will affect the mic in twilio?

//after call connected -> caller will here ringing sound untill receiver joins the call
func playSound() {
        guard let url = Bundle.main.url(forResource: "ringring", withExtension: "mp3") else { return }
        let session = AVAudioSession.sharedInstance()
        do {
            try session.setCategory(AVAudioSessionCategoryPlayAndRecord)
            try session.setMode(isAudioCall ? AVAudioSessionModeVoiceChat : AVAudioSessionModeVideoChat)
            try session.overrideOutputAudioPort(AVAudioSession.PortOverride.none)
            try session.setActive(true)
            player = try AVAudioPlayer(contentsOf: url, fileTypeHint: AVFileType.mp3.rawValue)
            
            guard let player = player else { return }
            player.numberOfLoops = 5
            player.prepareToPlay()
            player.play()
        } catch let error {
            print(error.localizedDescription)
        }
    }



//Before call connecting -> receiver side ring tone playing
 func playRingToneSound() {
        guard let url = Bundle.main.url(forResource: "ringtone", withExtension: "mp3") else { return }
        do {
            try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryAmbient)
            try AVAudioSession.sharedInstance().setActive(true)
            
            /* The following line is required for the player to work on iOS 11. Change the file type accordingly*/
            player = try AVAudioPlayer(contentsOf: url, fileTypeHint: AVFileType.mp3.rawValue)
            
            /* iOS 10 and earlier require the following line:
             player = try AVAudioPlayer(contentsOf: url, fileTypeHint: AVFileTypeMPEGLayer3) */
            
            guard let player = player else { return }
            player.numberOfLoops = 3
            player.prepareToPlay()
            player.play()
            
        } catch let error {
            print(error.localizedDescription)
        }
    }

**Comment by musheer-ahamed** [comment]
@ceaglest 
I have tested with VideoQuick start project. mic & audio was working fine. I have created one new view controller in my project and just copy-pasted VideoQuick code. Then also the same issue. The mic is not working when going to background & come foreground.
I have enabled background audio. Anything I missed in the setup? 



import UIKit
import TwilioVideo

class TwilioViewController: UIViewController {
    
    @IBOutlet weak var localPreview: VideoView!
    
    @IBOutlet weak var muteBtn: UIButton!
    @IBOutlet weak var statusLabel: UILabel!
    
    
    var room: Room?
    var camera: CameraSource?
    var localVideoTrack: LocalVideoTrack?
    var localAudioTrack: LocalAudioTrack?
    var remoteParticipant: RemoteParticipant?
    var remoteView: VideoView?
    var twilioRoom: TwilioRoom?
    var isFromReceiveCall = false
    var chatRoomDetails: ChatRoomDetails?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.startPreview()
        
        if isFromReceiveCall, let receiveCall = twilioRoom {
            performRoomConnect(accessToken: receiveCall.token, roomName: receiveCall.twilioRoom)
        }else {
            initiateCall(isAudioCall: false)
        }
    }
    
    func initiateCall(isAudioCall: Bool) {
        if Utils.isInternetReacheable(), let chatRoom = chatRoomDetails {
            HulloAPI.getInstance().initiateCall(makeCallObject: HulloPayDataSource.getInstance().getCallObject(isAudioCall: isAudioCall, chatRoomDetails: chatRoom, roomId: nil)) { (error, result) in
                if error != nil {
                    
                } else if let result = result {
                    print(result.twilioRoom)
                    self.twilioRoom = result
                    self.performRoomConnect(accessToken: result.token, roomName: result.twilioRoom)
                }
            }
        }
    }
    
    
    @IBAction func actionOnMuteBtn(_ sender: Any) {
        if (self.localAudioTrack != nil) {
            self.localAudioTrack?.isEnabled = !(self.localAudioTrack?.isEnabled)!
            
            // Update the button title
            if (self.localAudioTrack?.isEnabled == true) {
                self.muteBtn.setTitle("Mute", for: .normal)
            } else {
                self.muteBtn.setTitle("Unmute", for: .normal)
            }
        }
    }
    
    @IBAction func actionOnCallEndBtn(_ sender: Any) {
        self.room!.disconnect()
        logMessage(messageText: "Attempting to disconnect from room \(room!.name)")
    }
    
    func performRoomConnect(accessToken: String, roomName: String) {
        // Configure access token either from server or manually.
        // If the default wasn't changed, try fetching from server.
        
        // Prepare local media which we will share with Room Participants.
        self.prepareLocalMedia()
        
        // Preparing the connect options with the access token that we fetched (or hardcoded).
        let connectOptions = ConnectOptions(token: accessToken) { (builder) in
            
            // Use the local media that we prepared earlier.
            builder.audioTracks = self.localAudioTrack != nil ? [self.localAudioTrack!] : [LocalAudioTrack]()
            builder.videoTracks = self.localVideoTrack != nil ? [self.localVideoTrack!] : [LocalVideoTrack]()
            
            // Use the preferred audio codec
            if let preferredAudioCodec = Settings.shared.audioCodec {
                builder.preferredAudioCodecs = [preferredAudioCodec]
            }
            
            // Use the preferred video codec
            if let preferredVideoCodec = Settings.shared.videoCodec {
                builder.preferredVideoCodecs = [preferredVideoCodec]
            }
            
            // Use the preferred encoding parameters
            if let encodingParameters = Settings.shared.getEncodingParameters() {
                builder.encodingParameters = encodingParameters
            }

            // Use the preferred signaling region
            if let signalingRegion = Settings.shared.signalingRegion {
                builder.region = signalingRegion
            }
            
            // The name of the Room where the Client will attempt to connect to. Please note that if you pass an empty
            // Room `name`, the Client will create one for you. You can get the name or sid from any connected Room.
            builder.roomName = roomName
        }
        
        // Connect to the Room using the options we provided.
        room = TwilioVideoSDK.connect(options: connectOptions, delegate: self)
        
    }
    
    
    func startPreview() {
        if PlatformUtils.isSimulator {
            return
        }
        
        let frontCamera = CameraSource.captureDevice(position: .front)
        let backCamera = CameraSource.captureDevice(position: .back)
        
        if (frontCamera != nil || backCamera != nil) {
            
            let options = CameraSourceOptions { (builder) in
                if #available(iOS 13.0, *) {
                    // Track UIWindowScene events for the key window's scene.
                    // The example app disables multi-window support in the .plist (see UIApplicationSceneManifestKey).
                    builder.orientationTracker = UserInterfaceTracker(scene: UIApplication.shared.keyWindow!.windowScene!)
                }
            }
            // Preview our local camera track in the local video preview view.
            camera = CameraSource(options: options, delegate: self)
            localVideoTrack = LocalVideoTrack(source: camera!, enabled: true, name: "Camera")
            
            // Add renderer to video track for local preview
            localVideoTrack!.addRenderer(self.localPreview)
            logMessage(messageText: "Video track created")
            
            if (frontCamera != nil && backCamera != nil) {
                // We will flip camera on tap.
                let tap = UITapGestureRecognizer(target: self, action: #selector(flipCamera))
                self.localPreview.addGestureRecognizer(tap)
            }
            
            camera!.startCapture(device: frontCamera != nil ? frontCamera! : backCamera!) { (captureDevice, videoFormat, error) in
                if let error = error {
                    self.logMessage(messageText: "Capture failed with error.\ncode = \((error as NSError).code) error = \(error.localizedDescription)")
                } else {
                    self.localPreview.shouldMirror = (captureDevice.position == .front)
                }
            }
        }
        else {
            self.logMessage(messageText:"No front or back capture device found!")
        }
    }
    
    @objc func flipCamera() {
        var newDevice: AVCaptureDevice?

        if let camera = self.camera, let captureDevice = camera.device {
            if captureDevice.position == .front {
                newDevice = CameraSource.captureDevice(position: .back)
            } else {
                newDevice = CameraSource.captureDevice(position: .front)
            }

            if let newDevice = newDevice {
                camera.selectCaptureDevice(newDevice) { (captureDevice, videoFormat, error) in
                    if let error = error {
                        self.logMessage(messageText: "Error selecting capture device.\ncode = \((error as NSError).code) error = \(error.localizedDescription)")
                    } else {
                        self.localPreview.shouldMirror = (captureDevice.position == .front)
                    }
                }
            }
        }
    }
    
     func prepareLocalMedia() {

         // We will share local audio and video when we connect to the Room.

         // Create an audio track.
         if (localAudioTrack == nil) {
             localAudioTrack = LocalAudioTrack(options: nil, enabled: true, name: "Microphone")

             if (localAudioTrack == nil) {
                 logMessage(messageText: "Failed to create audio track")
             }
         }

         // Create a video track which captures from the camera.
         if (localVideoTrack == nil) {
             self.startPreview()
         }
    }
    
    func logMessage(messageText: String) {
        NSLog(messageText)
        let log = LagObj()
        log.message = messageText
        HulloPayRealm.getInstance().addLogDetails(roomDetails: log)
        statusLabel.text = messageText
    }
    
    func renderRemoteParticipant(participant : RemoteParticipant) -> Bool {
        // This example renders the first subscribed RemoteVideoTrack from the RemoteParticipant.
        let videoPublications = participant.remoteVideoTracks
        for publication in videoPublications {
            if let subscribedVideoTrack = publication.remoteTrack,
                publication.isTrackSubscribed {
                setupRemoteVideoView()
                subscribedVideoTrack.addRenderer(self.remoteView!)
                self.remoteParticipant = participant
                return true
            }
        }
        return false
    }
    
    func renderRemoteParticipants(participants : Array<RemoteParticipant>) {
        for participant in participants {
            // Find the first renderable track.
            if participant.remoteVideoTracks.count > 0,
                renderRemoteParticipant(participant: participant) {
                break
            }
        }
    }
    
    func cleanupRemoteParticipant() {
        if self.remoteParticipant != nil {
            self.remoteView?.removeFromSuperview()
            self.remoteView = nil
            self.remoteParticipant = nil
        }
    }
    
    func setupRemoteVideoView() {
        // Creating `VideoView` programmatically
        self.remoteView = VideoView(frame: CGRect.zero, delegate: self)
        
        self.view.insertSubview(self.remoteView!, at: 0)
        
        // `VideoView` supports scaleToFill, scaleAspectFill and scaleAspectFit
        // scaleAspectFit is the default mode when you create `VideoView` programmatically.
        self.remoteView!.contentMode = .scaleAspectFit;
        
        let centerX = NSLayoutConstraint(item: self.remoteView!,
                                         attribute: NSLayoutConstraint.Attribute.centerX,
                                         relatedBy: NSLayoutConstraint.Relation.equal,
                                         toItem: self.view,
                                         attribute: NSLayoutConstraint.Attribute.centerX,
                                         multiplier: 1,
                                         constant: 0);
        self.view.addConstraint(centerX)
        let centerY = NSLayoutConstraint(item: self.remoteView!,
                                         attribute: NSLayoutConstraint.Attribute.centerY,
                                         relatedBy: NSLayoutConstraint.Relation.equal,
                                         toItem: self.view,
                                         attribute: NSLayoutConstraint.Attribute.centerY,
                                         multiplier: 1,
                                         constant: 0);
        self.view.addConstraint(centerY)
        let width = NSLayoutConstraint(item: self.remoteView!,
                                       attribute: NSLayoutConstraint.Attribute.width,
                                       relatedBy: NSLayoutConstraint.Relation.equal,
                                       toItem: self.view,
                                       attribute: NSLayoutConstraint.Attribute.width,
                                       multiplier: 1,
                                       constant: 0);
        self.view.addConstraint(width)
        let height = NSLayoutConstraint(item: self.remoteView!,
                                        attribute: NSLayoutConstraint.Attribute.height,
                                        relatedBy: NSLayoutConstraint.Relation.equal,
                                        toItem: self.view,
                                        attribute: NSLayoutConstraint.Attribute.height,
                                        multiplier: 1,
                                        constant: 0);
        self.view.addConstraint(height)
    }
}

// MARK:- RoomDelegate
extension TwilioViewController : RoomDelegate {
    func roomDidConnect(room: Room) {
        logMessage(messageText: "Connected to room \(room.name) as \(room.localParticipant?.identity ?? "")")
        
        // This example only renders 1 RemoteVideoTrack at a time. Listen for all events to decide which track to render.
        for remoteParticipant in room.remoteParticipants {
            remoteParticipant.delegate = self
        }
    }
    
    func roomDidDisconnect(room: Room, error: Error?) {
        logMessage(messageText: "Disconnected from room \(room.name), error = \(String(describing: error))")
        self.cleanupRemoteParticipant()
        self.room = nil
        self.dismiss(animated: true, completion: nil)
    }
    
    func roomDidFailToConnect(room: Room, error: Error) {
        logMessage(messageText: "Failed to connect to room with error = \(String(describing: error))")
        self.room = nil
        
    }
    
    func roomIsReconnecting(room: Room, error: Error) {
        logMessage(messageText: "Reconnecting to room \(room.name), error = \(String(describing: error))")
    }
    
    func roomDidReconnect(room: Room) {
        logMessage(messageText: "Reconnected to room \(room.name)")
    }
    
    func participantDidConnect(room: Room, participant: RemoteParticipant) {
        // Listen for events from all Participants to decide which RemoteVideoTrack to render.
        participant.delegate = self
        
        logMessage(messageText: "Participant \(participant.identity) connected with \(participant.remoteAudioTracks.count) audio and \(participant.remoteVideoTracks.count) video tracks")
    }
    
    func participantDidDisconnect(room: Room, participant: RemoteParticipant) {
        logMessage(messageText: "Room \(room.name), Participant \(participant.identity) disconnected")
        // Nothing to do in this example. Subscription events are used to add/remove renderers.
    }
}

// MARK:- RemoteParticipantDelegate
extension TwilioViewController : RemoteParticipantDelegate {
    
    func remoteParticipantDidPublishVideoTrack(participant: RemoteParticipant, publication: RemoteVideoTrackPublication) {
        // Remote Participant has offered to share the video Track.
        
        logMessage(messageText: "Participant \(participant.identity) published \(publication.trackName) video track")
    }
    
    func remoteParticipantDidUnpublishVideoTrack(participant: RemoteParticipant, publication: RemoteVideoTrackPublication) {
        // Remote Participant has stopped sharing the video Track.
        
        logMessage(messageText: "Participant \(participant.identity) unpublished \(publication.trackName) video track")
    }
    
    func remoteParticipantDidPublishAudioTrack(participant: RemoteParticipant, publication: RemoteAudioTrackPublication) {
        // Remote Participant has offered to share the audio Track.
        
        logMessage(messageText: "Participant \(participant.identity) published \(publication.trackName) audio track")
    }
    
    func remoteParticipantDidUnpublishAudioTrack(participant: RemoteParticipant, publication: RemoteAudioTrackPublication) {
        // Remote Participant has stopped sharing the audio Track.
        
        logMessage(messageText: "Participant \(participant.identity) unpublished \(publication.trackName) audio track")
    }
    
    func didSubscribeToVideoTrack(videoTrack: RemoteVideoTrack, publication: RemoteVideoTrackPublication, participant: RemoteParticipant) {
        // The LocalParticipant is subscribed to the RemoteParticipant's video Track. Frames will begin to arrive now.
        
        logMessage(messageText: "Subscribed to \(publication.trackName) video track for Participant \(participant.identity)")
        
        if (self.remoteParticipant == nil) {
            _ = renderRemoteParticipant(participant: participant)
        }
    }
    
    func didUnsubscribeFromVideoTrack(videoTrack: RemoteVideoTrack, publication: RemoteVideoTrackPublication, participant: RemoteParticipant) {
        // We are unsubscribed from the remote Participant's video Track. We will no longer receive the
        // remote Participant's video.
        
        logMessage(messageText: "Unsubscribed from \(publication.trackName) video track for Participant \(participant.identity)")
        
        if self.remoteParticipant == participant {
            cleanupRemoteParticipant()
            
            // Find another Participant video to render, if possible.
            if var remainingParticipants = room?.remoteParticipants,
                let index = remainingParticipants.index(of: participant) {
                remainingParticipants.remove(at: index)
                renderRemoteParticipants(participants: remainingParticipants)
            }
        }
    }
    
    func didSubscribeToAudioTrack(audioTrack: RemoteAudioTrack, publication: RemoteAudioTrackPublication, participant: RemoteParticipant) {
        // We are subscribed to the remote Participant's audio Track. We will start receiving the
        // remote Participant's audio now.
        
        logMessage(messageText: "Subscribed to \(publication.trackName) audio track for Participant \(participant.identity)")
    }
    
    func didUnsubscribeFromAudioTrack(audioTrack: RemoteAudioTrack, publication: RemoteAudioTrackPublication, participant: RemoteParticipant) {
        // We are unsubscribed from the remote Participant's audio Track. We will no longer receive the
        // remote Participant's audio.
        
        logMessage(messageText: "Unsubscribed from \(publication.trackName) audio track for Participant \(participant.identity)")
    }
    
    func remoteParticipantDidEnableVideoTrack(participant: RemoteParticipant, publication: RemoteVideoTrackPublication) {
        logMessage(messageText: "Participant \(participant.identity) enabled \(publication.trackName) video track")
    }
    
    func remoteParticipantDidDisableVideoTrack(participant: RemoteParticipant, publication: RemoteVideoTrackPublication) {
        logMessage(messageText: "Participant \(participant.identity) disabled \(publication.trackName) video track")
    }
    
    func remoteParticipantDidEnableAudioTrack(participant: RemoteParticipant, publication: RemoteAudioTrackPublication) {
        logMessage(messageText: "Participant \(participant.identity) enabled \(publication.trackName) audio track")
    }
    
    func remoteParticipantDidDisableAudioTrack(participant: RemoteParticipant, publication: RemoteAudioTrackPublication) {
        logMessage(messageText: "Participant \(participant.identity) disabled \(publication.trackName) audio track")
    }
    
    func didFailToSubscribeToAudioTrack(publication: RemoteAudioTrackPublication, error: Error, participant: RemoteParticipant) {
        logMessage(messageText: "FailedToSubscribe \(publication.trackName) audio track, error = \(String(describing: error))")
    }
    
    func didFailToSubscribeToVideoTrack(publication: RemoteVideoTrackPublication, error: Error, participant: RemoteParticipant) {
        logMessage(messageText: "FailedToSubscribe \(publication.trackName) video track, error = \(String(describing: error))")
    }
}

// MARK:- VideoViewDelegate
extension TwilioViewController : VideoViewDelegate {
    func videoViewDimensionsDidChange(view: VideoView, dimensions: CMVideoDimensions) {
        self.view.setNeedsLayout()
    }
}

// MARK:- CameraSourceDelegate
extension TwilioViewController : CameraSourceDelegate {
    func cameraSourceDidFail(source: CameraSource, error: Error) {
        logMessage(messageText: "Camera source failed with error: \(error.localizedDescription)")
    }
}

**Comment by musheer-ahamed** [comment]
@ceaglest 
I have attached log during going background and come foreground.

**Comment by musheer-ahamed** [comment]
@ceaglest thanks for your support. Finally fixed this issue. While coming foreground audio session was changing in some other viewcontroller.

**Comment by ceaglest** [comment]
Hi @musheer-ahamed,

Sorry I couldn't do more to debug the issue. In `RM697de0e1fde5d17652e18ca475d21be9` I saw the audio get published multiple times with the same name resulting in `53304` errors. It sounds like you're no longer re-publishing audio and you figured out the AVAudioSession issue in your other view controller. This is what we expect in a typical integration. 👍 

Best,
Chris
