### ISSUE TITLE
Screen sharing example project not working

### ISSUE THREAD

**Issue by jamesal4** [twilio/video-quickstart-ios#537]
### Description

The example project for screen sharing is not working properly. The video does not appear as a track in the room.

### Steps to Reproduce

1. Create a test room
2. Get an access token for that room
3. Paste into line 33 of `video-quickstart-ios/ReplayKitExample/ReplayKitExample/ViewController.swift`
4. Run the app
5. Click Start Conference
6. Click Record Screen
5. Check the room participant tracks

#### Code

The only thing I changed about the project was the access token

#### Expected Behavior

The video and audio should connect to the room, and the video and audio tracks should appear in the room/recording logs

#### Actual Behavior

Only the audio track seems to connect to the room

#### Reproduces How Often

99%

#### Logs

Xcode logs with `TwilioVideoSDK.setLogLevel(.debug)`
[twilio_log.txt](https://github.com/twilio/video-quickstart-ios/files/4997469/twilio_log.txt)

#### Room settings

<img width="1164" alt="Screen Shot 2020-07-29 at 5 02 51 PM" src="https://user-images.githubusercontent.com/4512547/88853710-21d7be80-d1be-11ea-8f22-9926bbb6bdcc.png">

#### Video iOS SDK

3.5 via cocoapods

#### Xcode

11.5

#### iOS Version

13.3.1

#### iOS Device

iPhoneX - physical device

**Comment by piyushtank** [comment]
@jamesal4 ReplayKit sample app is functional and up to date. 

I looked into the room sid `RMcc8927af2fd2fba302ac996416ad1119` , you had only one participant connected to room `beef4`. There was no other participant in the Room. Also I noticed you were connected to the Room only for 2 seconds and then you had the call disconnected.  If you join `beef4` from other phone, you should see the screen shared by the first participant. Let me know if you have any questions.

**Comment by jamesal4** [comment]
I intentionally only had one participant connected because I was trying to debug the issue through twilio's website logs. I expected the video/audio recording to appear, but instead, I only saw the audio recording, and it lasted for the same amount of time I was connected through the app, 58 seconds. 

In a different room, I also tried having someone else connect, and they were able to connect but only heard the audio. I can't find that room id now, but if it would help, we can run that test again and give you the room id.

<img width="935" alt="Screen Shot 2020-08-13 at 11 17 28 AM" src="https://user-images.githubusercontent.com/4512547/90153130-95e59b00-dd56-11ea-9ad9-29cf076199b3.png">

**Comment by piyushtank** [comment]
@jamesal4 Apologies for the late response here. Were you able to resolve the problem. If not, please provide the room sid with both the participants in the Room. Thanks!

**Comment by finayev** [comment]
The issues still exists. Screen sharing feature from sample project is not working. Here's the SID of the room with 2 participants.
RM929d3751d5865c847f581b14e766d483

**Comment by SethVerishop** [comment]
oddly, I had this issue with the videoqucikstart project, but the screen recording works fine for me

**Comment by piyushtank** [comment]
I have passed RM929d3751d5865c847f581b14e766d483 to the backend team. I will keep you posted.

**Comment by piyushtank** [comment]
Unfortunately, I don't have any update on this issue. Are you still observing the issue? 
Wanted to let you know that we have shipped InApp screen sharing component in our 4.x SDK. And, we are currently working on making broadcast extension APIs part of SDKs. Try it out and let us know.

**Comment by piyushtank** [comment]
Please feel free to reopen or file another ticket if you run into any issues.

**Comment by gkotkin** [comment]
Maybe the reply is outdated, but still might help someone

Faced the same issue today: audio is played in the room, video is not displayed.
The root of the problem was that broadcaster and other room participant used different test authentication methods: the broadcaster used the manually generated access token while the receiving participant used the serverless backend provided by twilio tools:
twilio rtc:apps:video:deploy --authentication passcode

I made both my participants use the manually generated token and it worked like a charm.
