### ISSUE TITLE
"Command PhaseScriptExecution failed with a nonzero exit code" conflict only with firebase.

### ISSUE THREAD

**Issue by piyusharma13** [twilio/video-quickstart-ios#540]
### Description

My app is live and users are facing issues so when I am trying to integrate Firebase functionality with existing Twilio I am facing an issue related to "Command PhaseScriptExecution failed with a nonzero exit code"
This is happening only with firebase pods, I have tried other pods and everything is working fine.

### Steps to Reproduce -
1. Happening when I am archiving app. App builds and runs on simulator.

### Please note -
1. When I uncheck "Run script only when installing" app doesn't build on simulator.

### Tried following -
1. Disintegrated pods - cleared and reinstalled.
2. Cleared derived data.
3. Verified pods are not under source control (git).
#### I am using following pods:
pod 'TwilioVideo', '~> 3.4'
pod 'TwilioChatClient', '~> 3.1
pod 'Firebase/Crashlytics
pod 'Firebase/Analytics
### Versions

All relevant version information for the issue.

#### Video iOS SDK

[3.4 via CocoaPods]

#### Xcode

[11.5]

#### iOS Version

[Minimum - 11]

#### iOS Device

[Iphones only]

<img width="852" alt="Firebase" src="https://user-images.githubusercontent.com/21367878/90422177-1fd79000-e0d8-11ea-964e-fea13a0680a5.png">
<img width="389" alt="order" src="https://user-images.githubusercontent.com/21367878/90422187-249c4400-e0d8-11ea-9d9f-44a880e6c131.png">
<img width="1012" alt="Screenshot 2020-08-17 at 9 23 14 PM" src="https://user-images.githubusercontent.com/21367878/90422189-25cd7100-e0d8-11ea-938c-5882ffbea8ac.png">
<img width="873" alt="Twilio" src="https://user-images.githubusercontent.com/21367878/90422190-25cd7100-e0d8-11ea-9430-6d95cdbeebc6.png">

**Comment by piyusharma13** [comment]
Please find the response of Firebase support team:

<img width="652" alt="Screenshot 2020-08-18 at 9 40 03 AM" src="https://user-images.githubusercontent.com/21367878/90469626-f7cb4980-e136-11ea-92de-71048c3d6eb5.png">

Without adding another RunScript (just Twilio's one remaining), I am able to create an archive.

**Comment by piyushtank** [comment]
@piyusharma13 If you are using cocoapods, you may not be required to have an additional run script for `remove_arch` scripts. Our [documentation](https://www.twilio.com/docs/video/ios) has room for improvements which we will update in future.

Let me know if you have any questions.

**Comment by piyusharma13** [comment]
We are able to create an archive also with run Script by configuring build settings.
Thank you for the help.
