### ISSUE TITLE
Video Preview issue

### ISSUE THREAD

**Issue by AhmadDurrani579** [twilio/video-quickstart-ios#542]
Hello Mate Can you please let me know I am trying video call every thing is going perfect but the main problem is this that the preview of the other user not getting on my side thanks in advance

**Comment by piyushtank** [comment]
@AhmadDurrani579 Thanks for reaching out.

Have you tried using our VideoQuickStart [sample app](https://github.com/twilio/video-quickstart-ios/tree/master/VideoQuickStart) and see if you can reproduce the problem?

**Comment by AhmadDurrani579** [comment]
Hello Sir ,

Thank you for your email
In videoquickstart sample they use only 1 tvivideoview and i am using 2 one
for opponent user and one for my self just like whats app so than its.
Creating the problem


Thanks
Ahmad

**Comment by piyushtank** [comment]
@AhmadDurrani579  Can you sure that you have the VideoView attached to the VideoTrack. We have [iOS Video app](https://github.com/twilio/twilio-video-app-ios) which demonstrate multi-party use case. Please take a look and let us know if you have any qustions.

**Comment by AhmadDurrani579** [comment]
Hello Twilio/Video-Quickstart-Ios
Their is a permission for ios 14 so when i add its working i am closing
this issue thanks for your reply

**Comment by AhmadDurrani579** [comment]
In iOS 14 their is a permission for video call you have to put  this permission in info plist under  background mode = App provides Voice over IP services
In my case the app working fine in iOS 13 but in iOS 14 its not working so when i put this permission its start working
