### ISSUE TITLE
Setting up Server to generate Access Tokens [help wanted]

### ISSUE THREAD

**Issue by ksuhr1** [twilio/video-quickstart-ios#544]
### Description

Hi there, I want to set up a server for my iOS app that uses programmable video, based on the videoquickstart app. The examples I see to create an access token server is in different languages other than Swift. I'm not sure how to integrate say if I'm using a Node js example https://github.com/TwilioDevEd/video-access-token-server-node with my iOS project. I'd like to prepare my project for deployment and am confused about this section. Any help would be great. Thank you!

**Comment by designzoo-adrian** [comment]
You will need to deploy a server running the code to generate your access token that you can then use inside your IOS App to connect to a room. Your could deploy this code for production on heroku, aws etc. with a public url. e.g. https://mytwiliovideoapp.com
You would need to deploy a node app similar to the example, with all your config params e.g. api keys to be your own Twilio account details.
https://github.com/TwilioDevEd/video-access-token-server-node

**Essentially**
Inside the iOS App
- Make an API Call to your access token server (running on aws. heroku) to generate an access token and return the token from the api call
- Use the token in the room connect params when connecting to your video room in the IOS App

This section documents the various languages you can use to generate an access token and return it into your IOS/Web/Android App if you want to use something other than nodeJS.
https://www.twilio.com/docs/iam/access-tokens

**Comment by piyushtank** [comment]
See https://github.com/twilio/video-quickstart-ios#setup-an-access-token-server for more information.
