### ISSUE TITLE
Background Task 1 Warning

### ISSUE THREAD

**Issue by ksuhr1** [twilio/video-quickstart-ios#547]
### Description

Hi there. I have a view controller set up similar to the Design Consultant project https://www.twilio.com/blog/2017/10/ios-arkit-swift-twilio-programmable-video.html where I click one of two buttons(Designer or Consultant) on that will send me to the appropriate view controller that has a Preview setup where I would connect to a room such as in the videoQuickStart example. Once I am in the preview room, the camera is enabled and that is where i would type my room name and connect to the actual room. In this room I get this warning that I would like to fix because my app slows down dramatically later. I don't understand what is in the background task because I don't believe my app went in the background and stays in the foreground. Any help on debugging this and what the issue could be, would be great. The code is the same as the VideoQuickstart project except I added the view controller screen before the preview room to select which preview room I wanted to be in. Thank you!

2020-09-06 17:02:57.754138-0700 VideoQuickStart[7860:2085224] [BackgroundTask] Background Task 1 ("Called by TwilioVideo, from -[TVICameraCapturePipeline videoPipelineWillStartRunning]"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.
disconnecting camera

**Comment by ceaglest** [comment]
Hi @ksuhr1,

You would need to provide more information for us to help about the dramatic slowdown. However, the background task issue you mentioned can be fixed by upgrading to [3.6.0](https://www.twilio.com/docs/video/changelog-twilio-video-ios-version-3x#360-july-31-2020) or newer.

Best,
Chris

**Comment by ksuhr1** [comment]
Thank you @ceaglest! The update helped. The dramatic slowdown I have figured out!
