### ISSUE TITLE
Video call disconnected automatically

### ISSUE THREAD

**Issue by hand228** [twilio/video-quickstart-ios#553]
Description
I am using the Twillio CallKit for video calling in my app. It is working fine for every case but sometimes call disconnected automatically, while internet is working fine.

Steps to Reproduce
1. User A calls User B
2. User B picks the call
3. After 1 min 40s, the call was disconnected automatically

Expected Behavior
Call should not disconnect automatically.

Actual Behavior
Call disconnected sometimes automatically

Reproduces How Often
20-30%

Versions
3.6.0

Xcode
11.3.1

iOS Version
14

iOS Device
iPhone 7

Call Sid:
`RMe8a27fb5a0fc9ca3fbce3e5a82f876ff`

My issue is similar with this issue https://github.com/twilio/video-quickstart-ios/issues/197

**Comment by paynerc** [comment]
@hand228,

I have been looking into the details for the Room Sid provided and I see the following things:

1. The iPhone participant connects to the room at 2020-09-29T08:11:12.607Z.
2. The Android participant connects to the room at 2020-09-29T08:11:14.402Z
3. The iPhone participant sends a disconnect request to the room at 2020-09-29T08:13:10.813Z and is disconnected.
4. The Android participant sends a disconnect request to the room at 2020-09-29T08:13:10.992Z and is disconnected.

I don't see anything indicating that there was an error which caused the iPhone client to disconnect.

What would be very helpful in trying to diagnose this would be client side debug level logs to determine what is triggering the iPhone participant to send a disconnect. Is this something that you are able to reproduce and capture some logs to aid in troubleshooting this?

Ryan

**Comment by paynerc** [comment]
@hand228,

Following up to see if you have had luck collecting debug logs and if this is still reproducible.

Ryan

**Comment by hand228** [comment]
@paynerc 
Sorry for late reply.

We solved this problem, it's our mistake. We used a timer to check timeout when calling out but we forgot to invalidate it after connected.

Thanks for your support.

**Comment by hand228** [comment]
I will close this issue
