### ISSUE TITLE
Issue while recording my lecture on Microsoft teams

### ISSUE THREAD

**Issue by mosalhumaidi2020** [twilio/video-quickstart-ios#554]
iOS 14.01 IPad Pro, I got a message while I’m recording my lecture on Microsoft teams says “screen recording has stopped due to recording interrupted by multitasking and content resizing”  I just updated my Microsoft teams app2.0.22 . Any suggestions.
 
Thank you

**Comment by piyushtank** [comment]
@mosalhumaidi2020 Can you elaborate more on the used case. 

Can you please fill up the issue template, to give us the complete idea of what and how you are trying to achieve.

**Comment by paynerc** [comment]
Closing this issue as there has not been any activity for a few months.
