### ISSUE TITLE
iPhone is getting more heat & consuming more battery energy during video call

### ISSUE THREAD

**Issue by madhu-kadyala** [twilio/video-quickstart-ios#558]
Hi,
In my app, most of the iOS users are giving feedback as mobile is getting more heat & consuming more battery during video call. I have tried with 

builder.preferredVideoCodecs = [H264Codec()]
builder.encodingParameters = EncodingParameters(audioBitrate: 0, videoBitrate: 1 * 1024 * 1024)

but still receiving same feedback from users. Can you help me solve this issue.

SDK : 'TwilioVideo', '~> 3.5'

**Comment by piyushtank** [comment]
@madhu-kadyala can you please fill the issue template with iPhone versions, use case, device, iOS, etc. Also please mention list all iOS devices where you are observing the issue. And please make sure if you are observing the problem with our Quickstart or not. Thanks.

**Comment by piyushtank** [comment]
Closing an old ticket but feel free to reopen or file another if you run into any issues.
