### ISSUE TITLE
Transparency support

### ISSUE THREAD

**Issue by MarkoKostiv** [twilio/video-quickstart-ios#561]
We are looking for a way to send transparent frames with a segmented background.

Questions:
1. Does any of the supported codecs handle transparent images? Currently, we are using H.264, and it does not, apparently.
2. Is there any way to send additional metadata with a frame? E.g., binary bitmap or coordinates of the contour of the person

**Comment by ceaglest** [comment]
Hi @MarkoKostiv,

In answer to your questions.

1. Our SDK doesn't currently support video with an alpha channel / transparency.
2. You can send metadata using a DataTrack, but it isn't currently possible to attach the metadata on a per-frame, synchronized basis.

These are areas where our SDK could be improved. Unfortunately, I don't have a timeline on if/when we could offer transparency support.

Best,
Chris
