### ISSUE TITLE
Camera indicator (green dot) after disconnect : PRIVACY issue

### ISSUE THREAD

**Issue by Balasnest** [twilio/video-quickstart-ios#562]
Facing a problem with iOS 14 when the green dot appears even after the video ended or in disable mode? (It works for the microphone after disconnecting the call. But when I try to mute, it still persists. )

```
snippet call for disconnect:
[self.room disconnect]

Note: It successfully disconnected and also got events from the backend. 
```

The green dot still remains in the status bar indicating the camera usage from app. **USER** might take it seriously from a **PRIVACY /SECURITY** point of view.

**Comment by Balasnest** [comment]
https://github.com/blackuy/react-native-twilio-video-webrtc/issues/396

**Comment by Balasnest** [comment]
@ceaglest @paynerc  Need your assist here as earlier as possible. Thanks!

**Comment by paynerc** [comment]
@Balasnest,

The green dot is active anytime the camera is still capturing video, regardless if the room is connected or not. Be sure to call the `stopCapture` method of the `TVICameraSource` as well when you are no longer capturing video.

Ryan

**Comment by Balasnest** [comment]
@paynerc Thanks mate! It worked perfectly.
