### ISSUE TITLE
ReplayKitExample can't be built successfully-duplicate definition of category callKit

### ISSUE THREAD

**Issue by xiaozhouzhou** [twilio/video-quickstart-ios#565]
### Description

ReplayKitExample can't be built successfully .Could you help me ? 

![スクリーンショット 2020-10-29 16 07 39](https://user-images.githubusercontent.com/8065085/97542200-4f244a80-1a01-11eb-9e64-f9d91aa589b5.png)

#### Video iOS SDK

3.7.1

#### Xcode

11.6

#### iOS Version

[e.g. 11.2.6]

#### iOS Device

iphone 11 Pro(13.6)

**Comment by piyushtank** [comment]
@xiaozhouzhou Thanks for reaching out, we are not seeing the same problem while building the ReplayKitExample. Did you try with cocoapods ? Can you try fresh new project by pulling the repo and cocoapods installation ?

**Comment by paynerc** [comment]
@xiaozhouzhou,

Are you still experiencing this issue?

Ryan

**Comment by piyushtank** [comment]
Closing the ticket assuming the issue has been resolved. Feel free to reach out to us if you run into any issues.
