### ISSUE TITLE
Too many third party dependencies

### ISSUE THREAD

**Issue by thefaj** [twilio/video-quickstart-ios#567]
Could you please clean up this project and make it just use first party UIKit calls?
Cocoapods is pretty messy, and it seems like you could use Swift Package Manager to include TwilioVideo as its only dependency. All of the third party dependencies really obstruct quick onboarding for the Twilio Video project.

**Comment by paynerc** [comment]
@thefaj,

With the Twilio Video iOS 4.x release, it now is distributed via Swift Package Manager and the quick start applications in this repository consumes it via SPM.

Ryan

**Comment by thefaj** [comment]
@paynerc awesome!! Thanks for the update, too!
