### ISSUE TITLE
'DefaultAudioDevice' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by pkumawat34** [twilio/video-quickstart-ios#568]
import UIKit
import TwilioVoice
import TwilioVideo
import AVFoundation
import PushKit
import CallKit

class AudioCallVC: UIViewController {
        var audioDevice: DefaultAudioDevice = DefaultAudioDevice()
}

**Comment by smartphone-pro** [comment]
@pkumawat34 
Hello,
Did you solve the above issue?
I'm suffering from the same error.

**Comment by piyushtank** [comment]
@pkumawat34 The DefaultAudioDevice is defined in both voice and video SDKs. Have you tried using `TwilioVideoSDK.DefaultAudioDevice()`? Another option is to have a utility method in their respective swift file for voice and video to have get the approprite audio device of your choice.

**Comment by piyushtank** [comment]
Closing the ticket assuming the problem is resolved. Feel free to reach out to us if you run into any issues.

**Comment by DiegoQuimbo** [comment]
`TwilioVideoSDK.DefaultAudioDevice()` throw the following error: "Type 'TwilioVideoSDK' has no member 'DefaultAudioDevice'"
