### ISSUE TITLE
different between LocalVideoTrack and remoteVideoTrack

### ISSUE THREAD

**Issue by NALanhnt2** [twilio/video-quickstart-ios#569]
i have some task about ML on video call (virtual background). Everything is good on local LocalVideoTrack but when i use remoteVideoTrack, i have some problem (about memory leak)
i want to ask you. what is different between LocalVideoTrack and remoteVideoTrack
*sorry about my english"

**Comment by NALanhnt2** [comment]
@ceaglest help me please

**Comment by piyushtank** [comment]
@NALanhnt2 LocalVideoTrack and RemoteVideoTrack - both are VideoTracks, hence you can add renderer to either to get the video frames. The only difference is, LocalVideoTrack is used to send your (local participant's) video frames in a Room vs the RemoteVideoTrack represents the remote participant's video frames in a Room. 

Let me know if you have any questions.

**Comment by piyushtank** [comment]
Closing the ticket assuming the problem has been resolved. Feel free to reach out to us in case if you run into any issues.
