### ISSUE TITLE
Audio routes to device speakers instead of bluetooth earphones when using call kit to connect to room

### ISSUE THREAD

**Issue by kheldiente** [twilio/video-quickstart-ios#570]
### Description

No audio output observed in Bluetooth earphones when the user is connected to a room.

### Steps to Reproduce

1. Connect Bluetooth earphones.
2. Display call kit.
3. Instead of answering the call from Bluetooth earphones, **press the accept button on device**.
4. Connect to a room with an existing participant.

#### Expected Behavior

Bluetooth earphones should receive the audio output.

#### Actual Behavior

Device speakers receive the audio output instead.

#### Reproduces How Often

Always

#### Video iOS SDK

3.0

#### Xcode

11.6

#### iOS Version

13.6

#### iOS Device

iPhone 7

#### Findings

- I found out that this only occurs when the app is using call kit and accepts the call by pressing the accept button on the device.
- Bluetooth earphones work when call was accepted using Bluetooth earphone answer button.
- I ran the VideoCallKitQuickStart and it seems that it is also encountered there.
- I found a similar issue way back in 2018 - #236 
- This issue is similar to #468 with a difference of user was connected to a room first before connecting the Bluetooth earphones. I've tried this [code](https://github.com/twilio/video-quickstart-ios/issues/468#issuecomment-616746468) but it does not fix the problem.

**Comment by paynerc** [comment]
@kheldiente,

First off, I want to apologize for not getting back to you on this sooner. Are you still seeing this issue?

I have just tested this using the CallKit QuickStart, the latest TwilioVideo release (`4.2.0`) and my AirPods. I schedule the notification for the incoming call, lock the device and wait for the notification. I trigger it to simulate an incoming VoIP notification and get the CallKit incoming call UI. I accepted the incoming call on the iPhone and it joined the room and audio was flowing to and from my AirPods.

Can you take another look at this and let me know if you are still seeing the issue? At the moment I only have AirPods to test with. Were you seeing this with a particular bluetooth earphones or was it across various ones?

Again, sorry for the long response.

Ryan

**Comment by pyounesss** [comment]
Hello 

SDK Used: 5.2

we are still encountering the same issue with the same steps as this Ticket

is there any solution for this audio route ?
