### ISSUE TITLE
iOS 13 push notification not received 

### ISSUE THREAD

**Issue by umairAsifVeemed** [twilio/video-quickstart-ios#571]
func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {

if let chatClient = MessagesSingleton.shared.chatClient, chatClient.user != nil {
           chatClient.register(withNotificationToken: deviceToke) { (result) in
                print("pushToken \(result.isSuccessful())")
                if (!result.isSuccessful()) {
                    // try registration again or verify token
                }
            }
}

giving the following error

<<<<TwilioChatClient: 0x281842e00>>>> TNRegTransport[3]:        0x16f62b000 | 11/27/16:18:49.179 | WARNING  | 144    | TNRegTransport | Notification exception during registration: TNException: Address of Apn Binding must be a nonempty string of even number of hexadecimal characters, Public error code: 20001

**Comment by piyushtank** [comment]
@umairAsifVeemed This repo is meant for Twilio Video SDK. From the description it sounds like you need help in our chat SDK. Can you please open the issue on https://github.com/twilio/twilio-chat-demo-ios. 

Thanks!
