### ISSUE TITLE
Call disconnecting during call, If user locks the screen

### ISSUE THREAD

**Issue by musheer-ahamed** [twilio/video-quickstart-ios#583]
Hi, I am facing a call disconnecting issue during the call, if the user locks the screen. I'm using a call kit even though it's disconnecting.
Any suggestions for solving this issue?

**Comment by piyushtank** [comment]
Just like the native dialer, it's a CallKit behavior that when a user presses the lock screen it triggers `provider:performEndCallAction`. SDK doesn't disconnect the call by itself. 
See [this](https://github.com/twilio/video-quickstart-ios/blob/master/VideoCallKitQuickStart/ViewController%2BCallKit.swift#L72) example code for more information.
