### ISSUE TITLE
Unable to use Connect() method

### ISSUE THREAD

**Issue by hitgupta** [twilio/video-quickstart-ios#591]
I am using TwilioVideo SDK and on calling 
room = TwilioVideoSDK.connect(options: connectOptions, delegate: self)

I am getting compile time error : Type of expression is ambiguous without more context

Xcode being used : 12.2
Minimum iOS version 13
Swift 5

**Comment by paynerc** [comment]
@hitgupta,

Can you please enclose the code surrounding your `connect` call as it will be helpful to diagnose the issue.

Thank you,

Ryan

**Comment by ceaglest** [comment]
Hi,

Our examples have some [connection code](https://github.com/twilio/video-quickstart-ios/blob/680cd5d8f1f2f1a081bede13205da8f903e6c642/VideoQuickStart/ViewController.swift#L176) that you can reference. Let us know if you need any more help.

Best,
Chris
