### ISSUE TITLE
Enabling Video Recordings when creating Rooms

### ISSUE THREAD

**Issue by inertjade** [twilio/video-quickstart-ios#616]
### Description

Can you please confirm that [video recordings cannot be enabled](https://www.twilio.com/docs/video/tutorials/understanding-video-recordings-and-compositions#enabling-video-recordings) when creating Room using the iOS SDK for Twilio Video?

I understand that video Recording can be enabled in the Console, by navigating to [Room Settings](https://www.twilio.com/console/video/configure).

However, I am looking for a way to enable video recording on a per-room basis.

**Comment by paynerc** [comment]
@inertjade,

You are correct. If you are creating rooms via the Ad-Hoc method (by just connecting to a room via the SDK) room recordings are controlled via the settings in the console. To create certain rooms with recording enabled, you will need to use the [REST API](https://www.twilio.com/docs/video/api/rooms-resource#create-room) and pass in the `RecordParticipantsOnConnect` set to `true`. It should also be noted that recoding is only supported in Group Rooms.

Let me know if you have any further questions.

Ryan
