### ISSUE TITLE
Unable to hear participants Audio

### ISSUE THREAD

**Issue by razzz848** [twilio/video-quickstart-ios#618]
**Description**

Unable to hear the voice of A by C. A and B are able to hear both audio and see the video.When C calls to A , A attend the call (Hold and Accept) A and C facing audio issues Every-time (both A and C not able to hear Audio).  
  
**Note :**

 __**I face this issue latest Twilio Versions.In TwilioVideo (3.7.1) its working Fine(Both And C can able to hear Audio)**__

 
**Xcode**
12.4

 Is there anyone who had fixed this issue?
Can you help me?

**Comment by ceaglest** [comment]
Hi @razzz848,

I'm sorry to hear that audio is not working. Could you please provide debug logs from the device when this occurs? What is your application and is it using CallKit?

Best,
Chris
