### ISSUE TITLE
App not showing up in list of broadcasting applications

### ISSUE THREAD

**Issue by samitaha2** [twilio/video-quickstart-ios#622]
### Description

I am trying to integrate Twilio directly with my app and use the screenshare feature. My App is not showing up in the list of broadcasting applications when I click on RPSystemBroadcastPickerView

### Steps to Reproduce

I've mimicked exactly the same thing that the [Twilio Broadcast Sample App](https://github.com/twilio/video-quickstart-ios/tree/master/ReplayKitExample) has done. 

1.  I've created a new sample project 
2. I created an extension by going to file > new > target > broadcast upload extension 
3.  In the view controller of the first presented view I added: 
```
let broadcastPickerView = RPSystemBroadcastPickerView(frame: CGRect(x: 50, y: 100, width: 51, height: 51))
        view.addSubview(broadcastPickerView)
```
4. When I run my application, and click on the `RPSystemBroadcastPickerView` -- my app does not show up in this list. I'm at a loss because even if I take the Twilio app and strip it down to the bare bones, the app still shows up in the Broadcast Apps list.  
5. 
#### Expected Behavior

My application should show up in this list of apps 

#### Actual Behavior

My app is not present. 

#### Reproduces How Often

100%

#### Logs
Debug level logs are helpful when investigating issues. To enable debug level logging, add the following code to your application:

```.swift
TwilioVideoSDK.setLogLevel(.debug)
```

```
// Log output when the issue occurs
```

#### Xcode

12.5.1
#### iOS Version

14.4.2

#### iOS Device

iPad pro 11 inch

**Comment by samitaha2** [comment]
Odd. I am trying on another device and it shows up. It's not showing up on this specific device for some reason. I'm at a loss.

**Comment by ceaglest** [comment]
Hi @samitaha2,

This might be related to something about the first run experience when you debug an app with a broadcast extension. I'm not sure what to make of it either.

Best,
Chris
