### ISSUE TITLE
No audio in the headphones if they are already connected when the video starts

### ISSUE THREAD

**Issue by fpoisson** [twilio/video-quickstart-ios#93]
The headphones have to be disconnected and reconnected to the iOS device in order to hear the audio stream.

The issue was reproduced with the iOS SDK v1.0.0-beta5 and with the SDK v1.0.0-beta9.
Muting/unmuting does not solve the problem.

**Comment by dcdspace** [comment]
I too am experiencing this issue, any update? Thanks

**Comment by ptankTwilio** [comment]
@fpoisson @dcdspace I tried on  `1.0.0-beta9` and `beta10` using the latest QuickStart but I am not having any success in reproducing the problem. I was able to hear the remote participant's audio and the remote participant was able to hear mine. I tried with Apple's default earpods though.  Our QA team will try to reproduce this problem also. In the meantime, is it possible for you to enable following logs and send it to us? 

```      
TVIVideoClient.setLogLevel(.debug, module: .platform)
TVIVideoClient.setLogLevel(.debug, module: .webRTC) 
```

Thanks,
Piyush

**Comment by ptankTwilio** [comment]
@fpoisson @dcdspace Are you still running into the no audio issue?

**Comment by BorjaCloobing** [comment]
any news about this pivotal?

**Comment by piyushtank** [comment]
@BorjaCloobing Can you provide more information? The Device, iOS and SDK version ?

Is it possible to enable following logs and send them to us?
```
TVIVideoClient.setLogLevel(.debug, module: .platform)
TVIVideoClient.setLogLevel(.debug, module: .webRTC) 
```

Also, we were able to reproduce the no audio problem on iPad2/iOS9, we will look into it soon -
 https://github.com/twilio/video-quickstart-objc/issues/61

Please let me know if you have any question.
